// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: common/address.proto

package address

import (
	country "github.com/weebi-com/protos/common/country"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Address struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Street  string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	Code    string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	City    string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Country *country.Country       `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	// optional
	Latitude float64 `protobuf:"fixed64,5,opt,name=latitude,proto3" json:"latitude,omitempty"`
	// optional
	Longitude     float64 `protobuf:"fixed64,6,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_common_address_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_common_address_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_common_address_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetCountry() *country.Country {
	if x != nil {
		return x.Country
	}
	return nil
}

func (x *Address) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Address) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

var File_common_address_proto protoreflect.FileDescriptor

const file_common_address_proto_rawDesc = "" +
	"\n" +
	"\x14common/address.proto\x12\x14weebi.common.address\x1a\x14common/country.proto\"\xbc\x01\n" +
	"\aAddress\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x127\n" +
	"\acountry\x18\x04 \x01(\v2\x1d.weebi.common.country.CountryR\acountry\x12\x1a\n" +
	"\blatitude\x18\x05 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x06 \x01(\x01R\tlongitudeb\x06proto3"

var (
	file_common_address_proto_rawDescOnce sync.Once
	file_common_address_proto_rawDescData []byte
)

func file_common_address_proto_rawDescGZIP() []byte {
	file_common_address_proto_rawDescOnce.Do(func() {
		file_common_address_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_address_proto_rawDesc), len(file_common_address_proto_rawDesc)))
	})
	return file_common_address_proto_rawDescData
}

var file_common_address_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_address_proto_goTypes = []any{
	(*Address)(nil),         // 0: weebi.common.address.Address
	(*country.Country)(nil), // 1: weebi.common.country.Country
}
var file_common_address_proto_depIdxs = []int32{
	1, // 0: weebi.common.address.Address.country:type_name -> weebi.common.country.Country
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_address_proto_init() }
func file_common_address_proto_init() {
	if File_common_address_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_address_proto_rawDesc), len(file_common_address_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_address_proto_goTypes,
		DependencyIndexes: file_common_address_proto_depIdxs,
		MessageInfos:      file_common_address_proto_msgTypes,
	}.Build()
	File_common_address_proto = out.File
	file_common_address_proto_goTypes = nil
	file_common_address_proto_depIdxs = nil
}
