// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: boutique.proto

package boutique

import (
	address "github.com/weebi-com/protos/common/address"
	phone "github.com/weebi-com/protos/common/phone"
	device "github.com/weebi-com/protos/device"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BoutiqueMongo struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Boutique              *BoutiquePb            `protobuf:"bytes,1,opt,name=boutique,proto3" json:"boutique,omitempty"`
	BoutiqueId            string                 `protobuf:"bytes,2,opt,name=boutiqueId,proto3" json:"boutiqueId,omitempty"` // assigned by the server
	FirmId                string                 `protobuf:"bytes,3,opt,name=firmId,proto3" json:"firmId,omitempty"`
	ChainId               string                 `protobuf:"bytes,4,opt,name=chainId,proto3" json:"chainId,omitempty"`
	CreationTimestampUTC  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=creationTimestampUTC,proto3" json:"creationTimestampUTC,omitempty"`
	Name                  string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Devices               []*device.Device       `protobuf:"bytes,7,rep,name=devices,proto3" json:"devices,omitempty"`
	LastTouchTimestampUTC *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=lastTouchTimestampUTC,proto3" json:"lastTouchTimestampUTC,omitempty"`
	Logo                  []byte                 `protobuf:"bytes,9,opt,name=logo,proto3" json:"logo,omitempty"`
	// / extension here is a string, e.g. png or jpeg (!= enum in ArticlePhotoPb)
	LogoExtension        string            `protobuf:"bytes,10,opt,name=logoExtension,proto3" json:"logoExtension,omitempty"`
	IsDeleted            bool              `protobuf:"varint,11,opt,name=isDeleted,proto3" json:"isDeleted,omitempty"`
	DeletedBy            string            `protobuf:"bytes,12,opt,name=deletedBy,proto3" json:"deletedBy,omitempty"`   // userId who deleted it
	RestoredBy           string            `protobuf:"bytes,13,opt,name=restoredBy,proto3" json:"restoredBy,omitempty"` // userId who restored it (empty if never restored)
	AdditionalAttributes map[string]string `protobuf:"bytes,99,rep,name=additional_attributes,proto3" json:"additional_attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *BoutiqueMongo) Reset() {
	*x = BoutiqueMongo{}
	mi := &file_boutique_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoutiqueMongo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoutiqueMongo) ProtoMessage() {}

func (x *BoutiqueMongo) ProtoReflect() protoreflect.Message {
	mi := &file_boutique_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoutiqueMongo.ProtoReflect.Descriptor instead.
func (*BoutiqueMongo) Descriptor() ([]byte, []int) {
	return file_boutique_proto_rawDescGZIP(), []int{0}
}

func (x *BoutiqueMongo) GetBoutique() *BoutiquePb {
	if x != nil {
		return x.Boutique
	}
	return nil
}

func (x *BoutiqueMongo) GetBoutiqueId() string {
	if x != nil {
		return x.BoutiqueId
	}
	return ""
}

func (x *BoutiqueMongo) GetFirmId() string {
	if x != nil {
		return x.FirmId
	}
	return ""
}

func (x *BoutiqueMongo) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *BoutiqueMongo) GetCreationTimestampUTC() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationTimestampUTC
	}
	return nil
}

func (x *BoutiqueMongo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BoutiqueMongo) GetDevices() []*device.Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *BoutiqueMongo) GetLastTouchTimestampUTC() *timestamppb.Timestamp {
	if x != nil {
		return x.LastTouchTimestampUTC
	}
	return nil
}

func (x *BoutiqueMongo) GetLogo() []byte {
	if x != nil {
		return x.Logo
	}
	return nil
}

func (x *BoutiqueMongo) GetLogoExtension() string {
	if x != nil {
		return x.LogoExtension
	}
	return ""
}

func (x *BoutiqueMongo) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *BoutiqueMongo) GetDeletedBy() string {
	if x != nil {
		return x.DeletedBy
	}
	return ""
}

func (x *BoutiqueMongo) GetRestoredBy() string {
	if x != nil {
		return x.RestoredBy
	}
	return ""
}

func (x *BoutiqueMongo) GetAdditionalAttributes() map[string]string {
	if x != nil {
		return x.AdditionalAttributes
	}
	return nil
}

type BoutiquePb struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	BoutiqueId   string                 `protobuf:"bytes,1,opt,name=boutiqueId,proto3" json:"boutiqueId,omitempty"`
	CreationDate string                 `protobuf:"bytes,2,opt,name=creationDate,proto3" json:"creationDate,omitempty"`
	UpdateDate   string                 `protobuf:"bytes,3,opt,name=updateDate,proto3" json:"updateDate,omitempty"`
	// Deprecated: Marked as deprecated in boutique.proto.
	StatusUpdateDate string `protobuf:"bytes,4,opt,name=statusUpdateDate,proto3" json:"statusUpdateDate,omitempty"` // dont use this field, use lastTouchTimestampUTC instead
	// Deprecated: Marked as deprecated in boutique.proto.
	Status               bool              `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"` // dont use this field, use isDeleted instead
	Name                 string            `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Phone                *phone.Phone      `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	AddressFull          *address.Address  `protobuf:"bytes,8,opt,name=addressFull,proto3" json:"addressFull,omitempty"`
	Promo                float64           `protobuf:"fixed64,9,opt,name=promo,proto3" json:"promo,omitempty"`
	PromoStart           string            `protobuf:"bytes,10,opt,name=promoStart,proto3" json:"promoStart,omitempty"`
	PromoEnd             string            `protobuf:"bytes,11,opt,name=promoEnd,proto3" json:"promoEnd,omitempty"`
	IsDeleted            bool              `protobuf:"varint,12,opt,name=isDeleted,proto3" json:"isDeleted,omitempty"`
	DeletedBy            string            `protobuf:"bytes,13,opt,name=deletedBy,proto3" json:"deletedBy,omitempty"`   // userId who deleted it
	RestoredBy           string            `protobuf:"bytes,14,opt,name=restoredBy,proto3" json:"restoredBy,omitempty"` // userId who restored it (empty if never restored)
	Mail                 string            `protobuf:"bytes,15,opt,name=mail,proto3" json:"mail,omitempty"`
	AdditionalAttributes map[string]string `protobuf:"bytes,99,rep,name=additional_attributes,proto3" json:"additional_attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *BoutiquePb) Reset() {
	*x = BoutiquePb{}
	mi := &file_boutique_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoutiquePb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoutiquePb) ProtoMessage() {}

func (x *BoutiquePb) ProtoReflect() protoreflect.Message {
	mi := &file_boutique_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoutiquePb.ProtoReflect.Descriptor instead.
func (*BoutiquePb) Descriptor() ([]byte, []int) {
	return file_boutique_proto_rawDescGZIP(), []int{1}
}

func (x *BoutiquePb) GetBoutiqueId() string {
	if x != nil {
		return x.BoutiqueId
	}
	return ""
}

func (x *BoutiquePb) GetCreationDate() string {
	if x != nil {
		return x.CreationDate
	}
	return ""
}

func (x *BoutiquePb) GetUpdateDate() string {
	if x != nil {
		return x.UpdateDate
	}
	return ""
}

// Deprecated: Marked as deprecated in boutique.proto.
func (x *BoutiquePb) GetStatusUpdateDate() string {
	if x != nil {
		return x.StatusUpdateDate
	}
	return ""
}

// Deprecated: Marked as deprecated in boutique.proto.
func (x *BoutiquePb) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *BoutiquePb) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BoutiquePb) GetPhone() *phone.Phone {
	if x != nil {
		return x.Phone
	}
	return nil
}

func (x *BoutiquePb) GetAddressFull() *address.Address {
	if x != nil {
		return x.AddressFull
	}
	return nil
}

func (x *BoutiquePb) GetPromo() float64 {
	if x != nil {
		return x.Promo
	}
	return 0
}

func (x *BoutiquePb) GetPromoStart() string {
	if x != nil {
		return x.PromoStart
	}
	return ""
}

func (x *BoutiquePb) GetPromoEnd() string {
	if x != nil {
		return x.PromoEnd
	}
	return ""
}

func (x *BoutiquePb) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *BoutiquePb) GetDeletedBy() string {
	if x != nil {
		return x.DeletedBy
	}
	return ""
}

func (x *BoutiquePb) GetRestoredBy() string {
	if x != nil {
		return x.RestoredBy
	}
	return ""
}

func (x *BoutiquePb) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

func (x *BoutiquePb) GetAdditionalAttributes() map[string]string {
	if x != nil {
		return x.AdditionalAttributes
	}
	return nil
}

var File_boutique_proto protoreflect.FileDescriptor

const file_boutique_proto_rawDesc = "" +
	"\n" +
	"\x0eboutique.proto\x12\x0eweebi.boutique\x1a\x12common/phone.proto\x1a\x14common/address.proto\x1a\fdevice.proto\x1a\x18common/g_timestamp.proto\"\xd3\x05\n" +
	"\rBoutiqueMongo\x126\n" +
	"\bboutique\x18\x01 \x01(\v2\x1a.weebi.boutique.BoutiquePbR\bboutique\x12\x1e\n" +
	"\n" +
	"boutiqueId\x18\x02 \x01(\tR\n" +
	"boutiqueId\x12\x16\n" +
	"\x06firmId\x18\x03 \x01(\tR\x06firmId\x12\x18\n" +
	"\achainId\x18\x04 \x01(\tR\achainId\x12N\n" +
	"\x14creationTimestampUTC\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x14creationTimestampUTC\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12.\n" +
	"\adevices\x18\a \x03(\v2\x14.weebi.device.DeviceR\adevices\x12P\n" +
	"\x15lastTouchTimestampUTC\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x15lastTouchTimestampUTC\x12\x12\n" +
	"\x04logo\x18\t \x01(\fR\x04logo\x12$\n" +
	"\rlogoExtension\x18\n" +
	" \x01(\tR\rlogoExtension\x12\x1c\n" +
	"\tisDeleted\x18\v \x01(\bR\tisDeleted\x12\x1c\n" +
	"\tdeletedBy\x18\f \x01(\tR\tdeletedBy\x12\x1e\n" +
	"\n" +
	"restoredBy\x18\r \x01(\tR\n" +
	"restoredBy\x12m\n" +
	"\x15additional_attributes\x18c \x03(\v27.weebi.boutique.BoutiqueMongo.AdditionalAttributesEntryR\x15additional_attributes\x1aG\n" +
	"\x19AdditionalAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x0e\x10c\"\xbf\x05\n" +
	"\n" +
	"BoutiquePb\x12\x1e\n" +
	"\n" +
	"boutiqueId\x18\x01 \x01(\tR\n" +
	"boutiqueId\x12\"\n" +
	"\fcreationDate\x18\x02 \x01(\tR\fcreationDate\x12\x1e\n" +
	"\n" +
	"updateDate\x18\x03 \x01(\tR\n" +
	"updateDate\x12.\n" +
	"\x10statusUpdateDate\x18\x04 \x01(\tB\x02\x18\x01R\x10statusUpdateDate\x12\x1a\n" +
	"\x06status\x18\x05 \x01(\bB\x02\x18\x01R\x06status\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12/\n" +
	"\x05phone\x18\a \x01(\v2\x19.weebi.common.phone.PhoneR\x05phone\x12?\n" +
	"\vaddressFull\x18\b \x01(\v2\x1d.weebi.common.address.AddressR\vaddressFull\x12\x14\n" +
	"\x05promo\x18\t \x01(\x01R\x05promo\x12\x1e\n" +
	"\n" +
	"promoStart\x18\n" +
	" \x01(\tR\n" +
	"promoStart\x12\x1a\n" +
	"\bpromoEnd\x18\v \x01(\tR\bpromoEnd\x12\x1c\n" +
	"\tisDeleted\x18\f \x01(\bR\tisDeleted\x12\x1c\n" +
	"\tdeletedBy\x18\r \x01(\tR\tdeletedBy\x12\x1e\n" +
	"\n" +
	"restoredBy\x18\x0e \x01(\tR\n" +
	"restoredBy\x12\x12\n" +
	"\x04mail\x18\x0f \x01(\tR\x04mail\x12j\n" +
	"\x15additional_attributes\x18c \x03(\v24.weebi.boutique.BoutiquePb.AdditionalAttributesEntryR\x15additional_attributes\x1aG\n" +
	"\x19AdditionalAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x10\x10cb\x06proto3"

var (
	file_boutique_proto_rawDescOnce sync.Once
	file_boutique_proto_rawDescData []byte
)

func file_boutique_proto_rawDescGZIP() []byte {
	file_boutique_proto_rawDescOnce.Do(func() {
		file_boutique_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_boutique_proto_rawDesc), len(file_boutique_proto_rawDesc)))
	})
	return file_boutique_proto_rawDescData
}

var file_boutique_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_boutique_proto_goTypes = []any{
	(*BoutiqueMongo)(nil),         // 0: weebi.boutique.BoutiqueMongo
	(*BoutiquePb)(nil),            // 1: weebi.boutique.BoutiquePb
	nil,                           // 2: weebi.boutique.BoutiqueMongo.AdditionalAttributesEntry
	nil,                           // 3: weebi.boutique.BoutiquePb.AdditionalAttributesEntry
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*device.Device)(nil),         // 5: weebi.device.Device
	(*phone.Phone)(nil),           // 6: weebi.common.phone.Phone
	(*address.Address)(nil),       // 7: weebi.common.address.Address
}
var file_boutique_proto_depIdxs = []int32{
	1, // 0: weebi.boutique.BoutiqueMongo.boutique:type_name -> weebi.boutique.BoutiquePb
	4, // 1: weebi.boutique.BoutiqueMongo.creationTimestampUTC:type_name -> google.protobuf.Timestamp
	5, // 2: weebi.boutique.BoutiqueMongo.devices:type_name -> weebi.device.Device
	4, // 3: weebi.boutique.BoutiqueMongo.lastTouchTimestampUTC:type_name -> google.protobuf.Timestamp
	2, // 4: weebi.boutique.BoutiqueMongo.additional_attributes:type_name -> weebi.boutique.BoutiqueMongo.AdditionalAttributesEntry
	6, // 5: weebi.boutique.BoutiquePb.phone:type_name -> weebi.common.phone.Phone
	7, // 6: weebi.boutique.BoutiquePb.addressFull:type_name -> weebi.common.address.Address
	3, // 7: weebi.boutique.BoutiquePb.additional_attributes:type_name -> weebi.boutique.BoutiquePb.AdditionalAttributesEntry
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_boutique_proto_init() }
func file_boutique_proto_init() {
	if File_boutique_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_boutique_proto_rawDesc), len(file_boutique_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_boutique_proto_goTypes,
		DependencyIndexes: file_boutique_proto_depIdxs,
		MessageInfos:      file_boutique_proto_msgTypes,
	}.Build()
	File_boutique_proto = out.File
	file_boutique_proto_goTypes = nil
	file_boutique_proto_depIdxs = nil
}
