// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: btq_chain.proto

package btq_chain

import (
	boutique "github.com/weebi-com/protos/boutique"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Chain struct {
	state                  protoimpl.MessageState    `protogen:"open.v1"`
	ChainId                string                    `protobuf:"bytes,1,opt,name=chainId,proto3" json:"chainId,omitempty"`
	FirmId                 string                    `protobuf:"bytes,2,opt,name=firmId,proto3" json:"firmId,omitempty"`
	Name                   string                    `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Boutiques              []*boutique.BoutiqueMongo `protobuf:"bytes,4,rep,name=boutiques,proto3" json:"boutiques,omitempty"`
	CreationDateUTC        *timestamppb.Timestamp    `protobuf:"bytes,5,opt,name=creationDateUTC,proto3" json:"creationDateUTC,omitempty"`
	LastUpdateTimestampUTC *timestamppb.Timestamp    `protobuf:"bytes,6,opt,name=lastUpdateTimestampUTC,proto3" json:"lastUpdateTimestampUTC,omitempty"`
	LastUpdatedByuserId    string                    `protobuf:"bytes,7,opt,name=lastUpdatedByuserId,proto3" json:"lastUpdatedByuserId,omitempty"`
	IsDeleted              bool                      `protobuf:"varint,8,opt,name=isDeleted,proto3" json:"isDeleted,omitempty"`
	DeletedBy              string                    `protobuf:"bytes,9,opt,name=deletedBy,proto3" json:"deletedBy,omitempty"`    // userId who deleted it
	RestoredBy             string                    `protobuf:"bytes,10,opt,name=restoredBy,proto3" json:"restoredBy,omitempty"` // userId who restored it (empty if never restored)
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Chain) Reset() {
	*x = Chain{}
	mi := &file_btq_chain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chain) ProtoMessage() {}

func (x *Chain) ProtoReflect() protoreflect.Message {
	mi := &file_btq_chain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chain.ProtoReflect.Descriptor instead.
func (*Chain) Descriptor() ([]byte, []int) {
	return file_btq_chain_proto_rawDescGZIP(), []int{0}
}

func (x *Chain) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *Chain) GetFirmId() string {
	if x != nil {
		return x.FirmId
	}
	return ""
}

func (x *Chain) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Chain) GetBoutiques() []*boutique.BoutiqueMongo {
	if x != nil {
		return x.Boutiques
	}
	return nil
}

func (x *Chain) GetCreationDateUTC() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationDateUTC
	}
	return nil
}

func (x *Chain) GetLastUpdateTimestampUTC() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdateTimestampUTC
	}
	return nil
}

func (x *Chain) GetLastUpdatedByuserId() string {
	if x != nil {
		return x.LastUpdatedByuserId
	}
	return ""
}

func (x *Chain) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *Chain) GetDeletedBy() string {
	if x != nil {
		return x.DeletedBy
	}
	return ""
}

func (x *Chain) GetRestoredBy() string {
	if x != nil {
		return x.RestoredBy
	}
	return ""
}

type Chains struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chains        []*Chain               `protobuf:"bytes,1,rep,name=chains,proto3" json:"chains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chains) Reset() {
	*x = Chains{}
	mi := &file_btq_chain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chains) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chains) ProtoMessage() {}

func (x *Chains) ProtoReflect() protoreflect.Message {
	mi := &file_btq_chain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chains.ProtoReflect.Descriptor instead.
func (*Chains) Descriptor() ([]byte, []int) {
	return file_btq_chain_proto_rawDescGZIP(), []int{1}
}

func (x *Chains) GetChains() []*Chain {
	if x != nil {
		return x.Chains
	}
	return nil
}

var File_btq_chain_proto protoreflect.FileDescriptor

const file_btq_chain_proto_rawDesc = "" +
	"\n" +
	"\x0fbtq_chain.proto\x12\vweebi.chain\x1a\x0eboutique.proto\x1a\x18common/g_timestamp.proto\"\xb2\x03\n" +
	"\x05Chain\x12\x18\n" +
	"\achainId\x18\x01 \x01(\tR\achainId\x12\x16\n" +
	"\x06firmId\x18\x02 \x01(\tR\x06firmId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12;\n" +
	"\tboutiques\x18\x04 \x03(\v2\x1d.weebi.boutique.BoutiqueMongoR\tboutiques\x12D\n" +
	"\x0fcreationDateUTC\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0fcreationDateUTC\x12R\n" +
	"\x16lastUpdateTimestampUTC\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x16lastUpdateTimestampUTC\x120\n" +
	"\x13lastUpdatedByuserId\x18\a \x01(\tR\x13lastUpdatedByuserId\x12\x1c\n" +
	"\tisDeleted\x18\b \x01(\bR\tisDeleted\x12\x1c\n" +
	"\tdeletedBy\x18\t \x01(\tR\tdeletedBy\x12\x1e\n" +
	"\n" +
	"restoredBy\x18\n" +
	" \x01(\tR\n" +
	"restoredBy\"4\n" +
	"\x06Chains\x12*\n" +
	"\x06chains\x18\x01 \x03(\v2\x12.weebi.chain.ChainR\x06chainsb\x06proto3"

var (
	file_btq_chain_proto_rawDescOnce sync.Once
	file_btq_chain_proto_rawDescData []byte
)

func file_btq_chain_proto_rawDescGZIP() []byte {
	file_btq_chain_proto_rawDescOnce.Do(func() {
		file_btq_chain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_btq_chain_proto_rawDesc), len(file_btq_chain_proto_rawDesc)))
	})
	return file_btq_chain_proto_rawDescData
}

var file_btq_chain_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_btq_chain_proto_goTypes = []any{
	(*Chain)(nil),                  // 0: weebi.chain.Chain
	(*Chains)(nil),                 // 1: weebi.chain.Chains
	(*boutique.BoutiqueMongo)(nil), // 2: weebi.boutique.BoutiqueMongo
	(*timestamppb.Timestamp)(nil),  // 3: google.protobuf.Timestamp
}
var file_btq_chain_proto_depIdxs = []int32{
	2, // 0: weebi.chain.Chain.boutiques:type_name -> weebi.boutique.BoutiqueMongo
	3, // 1: weebi.chain.Chain.creationDateUTC:type_name -> google.protobuf.Timestamp
	3, // 2: weebi.chain.Chain.lastUpdateTimestampUTC:type_name -> google.protobuf.Timestamp
	0, // 3: weebi.chain.Chains.chains:type_name -> weebi.chain.Chain
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_btq_chain_proto_init() }
func file_btq_chain_proto_init() {
	if File_btq_chain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_btq_chain_proto_rawDesc), len(file_btq_chain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_btq_chain_proto_goTypes,
		DependencyIndexes: file_btq_chain_proto_depIdxs,
		MessageInfos:      file_btq_chain_proto_msgTypes,
	}.Build()
	File_btq_chain_proto = out.File
	file_btq_chain_proto_goTypes = nil
	file_btq_chain_proto_depIdxs = nil
}
