// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: common/g_common.proto

package g_common

import (
	empty "github.com/weebi-com/protos/common/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusResponse_Type int32

const (
	StatusResponse_SUCCESS StatusResponse_Type = 0
	StatusResponse_ERROR   StatusResponse_Type = 1
	StatusResponse_CREATED StatusResponse_Type = 2
	StatusResponse_UPDATED StatusResponse_Type = 3
	StatusResponse_DELETED StatusResponse_Type = 4
)

// Enum value maps for StatusResponse_Type.
var (
	StatusResponse_Type_name = map[int32]string{
		0: "SUCCESS",
		1: "ERROR",
		2: "CREATED",
		3: "UPDATED",
		4: "DELETED",
	}
	StatusResponse_Type_value = map[string]int32{
		"SUCCESS": 0,
		"ERROR":   1,
		"CREATED": 2,
		"UPDATED": 3,
		"DELETED": 4,
	}
)

func (x StatusResponse_Type) Enum() *StatusResponse_Type {
	p := new(StatusResponse_Type)
	*p = x
	return p
}

func (x StatusResponse_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusResponse_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_common_g_common_proto_enumTypes[0].Descriptor()
}

func (StatusResponse_Type) Type() protoreflect.EnumType {
	return &file_common_g_common_proto_enumTypes[0]
}

func (x StatusResponse_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusResponse_Type.Descriptor instead.
func (StatusResponse_Type) EnumDescriptor() ([]byte, []int) {
	return file_common_g_common_proto_rawDescGZIP(), []int{0, 0}
}

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN         HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING         HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING     HealthCheckResponse_ServingStatus = 2
	HealthCheckResponse_SERVICE_UNKNOWN HealthCheckResponse_ServingStatus = 3 // Used only by the Watch method.
)

// Enum value maps for HealthCheckResponse_ServingStatus.
var (
	HealthCheckResponse_ServingStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
		3: "SERVICE_UNKNOWN",
	}
	HealthCheckResponse_ServingStatus_value = map[string]int32{
		"UNKNOWN":         0,
		"SERVING":         1,
		"NOT_SERVING":     2,
		"SERVICE_UNKNOWN": 3,
	}
)

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_g_common_proto_enumTypes[1].Descriptor()
}

func (HealthCheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_common_g_common_proto_enumTypes[1]
}

func (x HealthCheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ServingStatus.Descriptor instead.
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_g_common_proto_rawDescGZIP(), []int{1, 0}
}

// A transfer object suitable for stream and non-stream error
type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // google.protobuf.Timestamp
	Type          StatusResponse_Type    `protobuf:"varint,2,opt,name=type,proto3,enum=google.retail.common.StatusResponse_Type" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_common_g_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_g_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_common_g_common_proto_rawDescGZIP(), []int{0}
}

func (x *StatusResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *StatusResponse) GetType() StatusResponse_Type {
	if x != nil {
		return x.Type
	}
	return StatusResponse_SUCCESS
}

func (x *StatusResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=google.retail.common.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_common_g_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_g_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_common_g_common_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

var File_common_g_common_proto protoreflect.FileDescriptor

const file_common_g_common_proto_rawDesc = "" +
	"\n" +
	"\x15common/g_common.proto\x12\x14google.retail.common\x1a\x12common/empty.proto\x1a\x18common/g_timestamp.proto\"\xfa\x01\n" +
	"\x0eStatusResponse\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12=\n" +
	"\x04type\x18\x02 \x01(\x0e2).google.retail.common.StatusResponse.TypeR\x04type\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"E\n" +
	"\x04Type\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\t\n" +
	"\x05ERROR\x10\x01\x12\v\n" +
	"\aCREATED\x10\x02\x12\v\n" +
	"\aUPDATED\x10\x03\x12\v\n" +
	"\aDELETED\x10\x04\"\xb7\x01\n" +
	"\x13HealthCheckResponse\x12O\n" +
	"\x06status\x18\x01 \x01(\x0e27.google.retail.common.HealthCheckResponse.ServingStatusR\x06status\"O\n" +
	"\rServingStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x02\x12\x13\n" +
	"\x0fSERVICE_UNKNOWN\x10\x032U\n" +
	"\x06Status\x12K\n" +
	"\x03Get\x12\x19.weebi.common.empty.Empty\x1a).google.retail.common.HealthCheckResponseb\x06proto3"

var (
	file_common_g_common_proto_rawDescOnce sync.Once
	file_common_g_common_proto_rawDescData []byte
)

func file_common_g_common_proto_rawDescGZIP() []byte {
	file_common_g_common_proto_rawDescOnce.Do(func() {
		file_common_g_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_g_common_proto_rawDesc), len(file_common_g_common_proto_rawDesc)))
	})
	return file_common_g_common_proto_rawDescData
}

var file_common_g_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_common_g_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_g_common_proto_goTypes = []any{
	(StatusResponse_Type)(0),               // 0: google.retail.common.StatusResponse.Type
	(HealthCheckResponse_ServingStatus)(0), // 1: google.retail.common.HealthCheckResponse.ServingStatus
	(*StatusResponse)(nil),                 // 2: google.retail.common.StatusResponse
	(*HealthCheckResponse)(nil),            // 3: google.retail.common.HealthCheckResponse
	(*timestamppb.Timestamp)(nil),          // 4: google.protobuf.Timestamp
	(*empty.Empty)(nil),                    // 5: weebi.common.empty.Empty
}
var file_common_g_common_proto_depIdxs = []int32{
	4, // 0: google.retail.common.StatusResponse.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: google.retail.common.StatusResponse.type:type_name -> google.retail.common.StatusResponse.Type
	1, // 2: google.retail.common.HealthCheckResponse.status:type_name -> google.retail.common.HealthCheckResponse.ServingStatus
	5, // 3: google.retail.common.Status.Get:input_type -> weebi.common.empty.Empty
	3, // 4: google.retail.common.Status.Get:output_type -> google.retail.common.HealthCheckResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_common_g_common_proto_init() }
func file_common_g_common_proto_init() {
	if File_common_g_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_g_common_proto_rawDesc), len(file_common_g_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_g_common_proto_goTypes,
		DependencyIndexes: file_common_g_common_proto_depIdxs,
		EnumInfos:         file_common_g_common_proto_enumTypes,
		MessageInfos:      file_common_g_common_proto_msgTypes,
	}.Build()
	File_common_g_common_proto = out.File
	file_common_g_common_proto_goTypes = nil
	file_common_g_common_proto_depIdxs = nil
}
