// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: fence_service.proto

package service

import (
	context "context"
	btq_chain "github.com/weebi-com/protos/btq_chain"
	chained_ids "github.com/weebi-com/protos/common/chained_ids"
	empty "github.com/weebi-com/protos/common/empty"
	g_common "github.com/weebi-com/protos/common/g_common"
	device "github.com/weebi-com/protos/device"
	firm "github.com/weebi-com/protos/firm"
	user "github.com/weebi-com/protos/user"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FenceService_HealthCheck_FullMethodName                  = "/weebi.fence.service.FenceService/healthCheck"
	FenceService_SignUp_FullMethodName                       = "/weebi.fence.service.FenceService/signUp"
	FenceService_AuthenticateWithCredentials_FullMethodName  = "/weebi.fence.service.FenceService/authenticateWithCredentials"
	FenceService_AuthenticateWithRefreshToken_FullMethodName = "/weebi.fence.service.FenceService/authenticateWithRefreshToken"
	FenceService_Logout_FullMethodName                       = "/weebi.fence.service.FenceService/logout"
	FenceService_RequestPasswordReset_FullMethodName         = "/weebi.fence.service.FenceService/requestPasswordReset"
	FenceService_ConfirmPasswordReset_FullMethodName         = "/weebi.fence.service.FenceService/confirmPasswordReset"
	FenceService_CreateFirm_FullMethodName                   = "/weebi.fence.service.FenceService/createFirm"
	FenceService_ReadOneFirm_FullMethodName                  = "/weebi.fence.service.FenceService/readOneFirm"
	FenceService_CreatePendingUser_FullMethodName            = "/weebi.fence.service.FenceService/createPendingUser"
	FenceService_ReadOneUser_FullMethodName                  = "/weebi.fence.service.FenceService/readOneUser"
	FenceService_ReadAllUsers_FullMethodName                 = "/weebi.fence.service.FenceService/readAllUsers"
	FenceService_UpdateOneUser_FullMethodName                = "/weebi.fence.service.FenceService/updateOneUser"
	FenceService_UpdateUserPassword_FullMethodName           = "/weebi.fence.service.FenceService/updateUserPassword"
	FenceService_DeleteOneUser_FullMethodName                = "/weebi.fence.service.FenceService/deleteOneUser"
	FenceService_MarkEmailVerified_FullMethodName            = "/weebi.fence.service.FenceService/markEmailVerified"
	FenceService_UpdateSubscriberId_FullMethodName           = "/weebi.fence.service.FenceService/updateSubscriberId"
	FenceService_CreateOneChain_FullMethodName               = "/weebi.fence.service.FenceService/createOneChain"
	FenceService_ReadAllChains_FullMethodName                = "/weebi.fence.service.FenceService/readAllChains"
	FenceService_UpdateOneChain_FullMethodName               = "/weebi.fence.service.FenceService/updateOneChain"
	FenceService_DeleteOneChain_FullMethodName               = "/weebi.fence.service.FenceService/deleteOneChain"
	FenceService_CreateOneBoutique_FullMethodName            = "/weebi.fence.service.FenceService/createOneBoutique"
	FenceService_ReadOneBoutique_FullMethodName              = "/weebi.fence.service.FenceService/readOneBoutique"
	FenceService_UpdateOneBoutique_FullMethodName            = "/weebi.fence.service.FenceService/updateOneBoutique"
	FenceService_DeleteOneBoutique_FullMethodName            = "/weebi.fence.service.FenceService/deleteOneBoutique"
	FenceService_RestoreOneBoutique_FullMethodName           = "/weebi.fence.service.FenceService/restoreOneBoutique"
	FenceService_ReadAllBoutiques_FullMethodName             = "/weebi.fence.service.FenceService/readAllBoutiques"
	FenceService_IsADeviceInChain_FullMethodName             = "/weebi.fence.service.FenceService/isADeviceInChain"
	FenceService_ReadDevices_FullMethodName                  = "/weebi.fence.service.FenceService/readDevices"
	FenceService_GenerateCodeForPairingDevice_FullMethodName = "/weebi.fence.service.FenceService/generateCodeForPairingDevice"
	FenceService_ReadOnePendingDevice_FullMethodName         = "/weebi.fence.service.FenceService/readOnePendingDevice"
	FenceService_CreateDevice_FullMethodName                 = "/weebi.fence.service.FenceService/createDevice"
	FenceService_UpdateDevicePassword_FullMethodName         = "/weebi.fence.service.FenceService/updateDevicePassword"
	FenceService_DeleteOneDevice_FullMethodName              = "/weebi.fence.service.FenceService/deleteOneDevice"
)

// FenceServiceClient is the client API for FenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// / boutiques & users
type FenceServiceClient interface {
	// / Health check with version information
	HealthCheck(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*HealthCheckWeebiResponse, error)
	SignUp(ctx context.Context, in *user.SignUpRequest, opts ...grpc.CallOption) (*user.SignUpResponse, error)
	AuthenticateWithCredentials(ctx context.Context, in *Credentials, opts ...grpc.CallOption) (*Tokens, error)
	AuthenticateWithRefreshToken(ctx context.Context, in *RefreshToken, opts ...grpc.CallOption) (*Tokens, error)
	// / Web session logout - invalidates session server-side. Envoy clears the cookie on success.
	Logout(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	// Password reset functionality
	RequestPasswordReset(ctx context.Context, in *PasswordResetRequest, opts ...grpc.CallOption) (*g_common.StatusResponse, error)
	ConfirmPasswordReset(ctx context.Context, in *PasswordResetConfirmRequest, opts ...grpc.CallOption) (*g_common.StatusResponse, error)
	// / only one firm per 'company'
	// / 1. user signup and get a userId & create firm permission
	// / 2. A. user create a firm
	// / Chain and Boutique will be created by default and will use the same firmId
	// / Since createFirm also updates user permission, clientApp needs to reauthent using refresh right after
	// / 2. B. user joins a firm is a different use case detailed in createPendingUser rpc
	CreateFirm(ctx context.Context, in *firm.CreateFirmRequest, opts ...grpc.CallOption) (*firm.CreateFirmResponse, error)
	ReadOneFirm(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*firm.Firm, error)
	CreatePendingUser(ctx context.Context, in *user.PendingUserRequest, opts ...grpc.CallOption) (*user.PendingUserResponse, error)
	ReadOneUser(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*ReadOneUserResponse, error)
	// / Presumably, until 2030 firms will have max 9 users, why bother filter ?
	ReadAllUsers(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*UsersPublic, error)
	// real update, not an upsert, does nothing if user not found
	UpdateOneUser(ctx context.Context, in *user.UserPublic, opts ...grpc.CallOption) (*g_common.StatusResponse, error)
	UpdateUserPassword(ctx context.Context, in *PasswordUpdateRequest, opts ...grpc.CallOption) (*g_common.StatusResponse, error)
	DeleteOneUser(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*g_common.StatusResponse, error)
	// Email verification - marks a user's email as verified
	MarkEmailVerified(ctx context.Context, in *MarkEmailVerifiedRequest, opts ...grpc.CallOption) (*g_common.StatusResponse, error)
	// Update subscriber ID - links a user to a newsletter subscriber
	UpdateSubscriberId(ctx context.Context, in *UpdateSubscriberIdRequest, opts ...grpc.CallOption) (*g_common.StatusResponse, error)
	CreateOneChain(ctx context.Context, in *btq_chain.Chain, opts ...grpc.CallOption) (*g_common.StatusResponse, error)
	ReadAllChains(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ReadAllChainsResponse, error)
	// only update fiels not boutiques, not upsert, do nothing if unfound
	UpdateOneChain(ctx context.Context, in *ChainRequest, opts ...grpc.CallOption) (*g_common.StatusResponse, error)
	// / hard/complete delete
	DeleteOneChain(ctx context.Context, in *ChainRequest, opts ...grpc.CallOption) (*g_common.StatusResponse, error)
	CreateOneBoutique(ctx context.Context, in *BoutiqueRequest, opts ...grpc.CallOption) (*g_common.StatusResponse, error)
	ReadOneBoutique(ctx context.Context, in *BoutiqueRequest, opts ...grpc.CallOption) (*BoutiqueResponse, error)
	// / real update, not upsert, do nothing if unfound
	UpdateOneBoutique(ctx context.Context, in *BoutiqueRequest, opts ...grpc.CallOption) (*g_common.StatusResponse, error)
	// / soft delete - marks boutique as deleted
	DeleteOneBoutique(ctx context.Context, in *BoutiqueRequest, opts ...grpc.CallOption) (*g_common.StatusResponse, error)
	// / restore a soft-deleted boutique
	RestoreOneBoutique(ctx context.Context, in *BoutiqueRequest, opts ...grpc.CallOption) (*g_common.StatusResponse, error)
	// / returns all active boutiques across all chains (filters out deleted ones)
	ReadAllBoutiques(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ReadAllBoutiquesResponse, error)
	// / scans all firm's devices, disregarding user rights
	// / used both in :
	// / weebi_app signups to REQUIRE that user pushes device data
	// / weebi_app device linking to PREVENT user from pushing data, pulling only
	// will be false by default, which is safer since it avoids corrupting data when linking new device that potentially weebi_app with different data
	// == isOneDevice at least
	IsADeviceInChain(ctx context.Context, in *ReadDevicesRequest, opts ...grpc.CallOption) (*IsADeviceInChainResponse, error)
	// / return only device visible according to user rights
	ReadDevices(ctx context.Context, in *ReadDevicesRequest, opts ...grpc.CallOption) (*device.Devices, error)
	// / device enrolment follows a different process than user enrolment
	// / generateCodeForPairingDevice is called by web app, it includes chainId and boutiqueId
	// / A device belongs to a boutique
	// TODO rename this create
	GenerateCodeForPairingDevice(ctx context.Context, in *chained_ids.ChainIdAndboutiqueId, opts ...grpc.CallOption) (*CodeForPairingDevice, error)
	// / webapp listens to deviceStream awaiting PoS app to createDevice by typing the code
	ReadOnePendingDevice(ctx context.Context, in *ReadDeviceBtqRequest, opts ...grpc.CallOption) (*device.Device, error)
	// / createDevice is called by mobile/desktop app
	// / await lasts for 2 minutes (to be tested)
	// / remove pending
	CreateDevice(ctx context.Context, in *PendingDeviceRequest, opts ...grpc.CallOption) (*CreateDeviceResponse, error)
	// / removed as it brings a security risk
	// / rpc authenticateWithDevice (DeviceCredentials) returns (Tokens);
	UpdateDevicePassword(ctx context.Context, in *UpdateDevicePasswordRequest, opts ...grpc.CallOption) (*g_common.StatusResponse, error)
	// / hard/forever delete
	DeleteOneDevice(ctx context.Context, in *DeleteDeviceRequest, opts ...grpc.CallOption) (*g_common.StatusResponse, error)
}

type fenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFenceServiceClient(cc grpc.ClientConnInterface) FenceServiceClient {
	return &fenceServiceClient{cc}
}

func (c *fenceServiceClient) HealthCheck(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*HealthCheckWeebiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckWeebiResponse)
	err := c.cc.Invoke(ctx, FenceService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fenceServiceClient) SignUp(ctx context.Context, in *user.SignUpRequest, opts ...grpc.CallOption) (*user.SignUpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(user.SignUpResponse)
	err := c.cc.Invoke(ctx, FenceService_SignUp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fenceServiceClient) AuthenticateWithCredentials(ctx context.Context, in *Credentials, opts ...grpc.CallOption) (*Tokens, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Tokens)
	err := c.cc.Invoke(ctx, FenceService_AuthenticateWithCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fenceServiceClient) AuthenticateWithRefreshToken(ctx context.Context, in *RefreshToken, opts ...grpc.CallOption) (*Tokens, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Tokens)
	err := c.cc.Invoke(ctx, FenceService_AuthenticateWithRefreshToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fenceServiceClient) Logout(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, FenceService_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fenceServiceClient) RequestPasswordReset(ctx context.Context, in *PasswordResetRequest, opts ...grpc.CallOption) (*g_common.StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(g_common.StatusResponse)
	err := c.cc.Invoke(ctx, FenceService_RequestPasswordReset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fenceServiceClient) ConfirmPasswordReset(ctx context.Context, in *PasswordResetConfirmRequest, opts ...grpc.CallOption) (*g_common.StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(g_common.StatusResponse)
	err := c.cc.Invoke(ctx, FenceService_ConfirmPasswordReset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fenceServiceClient) CreateFirm(ctx context.Context, in *firm.CreateFirmRequest, opts ...grpc.CallOption) (*firm.CreateFirmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(firm.CreateFirmResponse)
	err := c.cc.Invoke(ctx, FenceService_CreateFirm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fenceServiceClient) ReadOneFirm(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*firm.Firm, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(firm.Firm)
	err := c.cc.Invoke(ctx, FenceService_ReadOneFirm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fenceServiceClient) CreatePendingUser(ctx context.Context, in *user.PendingUserRequest, opts ...grpc.CallOption) (*user.PendingUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(user.PendingUserResponse)
	err := c.cc.Invoke(ctx, FenceService_CreatePendingUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fenceServiceClient) ReadOneUser(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*ReadOneUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadOneUserResponse)
	err := c.cc.Invoke(ctx, FenceService_ReadOneUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fenceServiceClient) ReadAllUsers(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*UsersPublic, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UsersPublic)
	err := c.cc.Invoke(ctx, FenceService_ReadAllUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fenceServiceClient) UpdateOneUser(ctx context.Context, in *user.UserPublic, opts ...grpc.CallOption) (*g_common.StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(g_common.StatusResponse)
	err := c.cc.Invoke(ctx, FenceService_UpdateOneUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fenceServiceClient) UpdateUserPassword(ctx context.Context, in *PasswordUpdateRequest, opts ...grpc.CallOption) (*g_common.StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(g_common.StatusResponse)
	err := c.cc.Invoke(ctx, FenceService_UpdateUserPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fenceServiceClient) DeleteOneUser(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*g_common.StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(g_common.StatusResponse)
	err := c.cc.Invoke(ctx, FenceService_DeleteOneUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fenceServiceClient) MarkEmailVerified(ctx context.Context, in *MarkEmailVerifiedRequest, opts ...grpc.CallOption) (*g_common.StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(g_common.StatusResponse)
	err := c.cc.Invoke(ctx, FenceService_MarkEmailVerified_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fenceServiceClient) UpdateSubscriberId(ctx context.Context, in *UpdateSubscriberIdRequest, opts ...grpc.CallOption) (*g_common.StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(g_common.StatusResponse)
	err := c.cc.Invoke(ctx, FenceService_UpdateSubscriberId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fenceServiceClient) CreateOneChain(ctx context.Context, in *btq_chain.Chain, opts ...grpc.CallOption) (*g_common.StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(g_common.StatusResponse)
	err := c.cc.Invoke(ctx, FenceService_CreateOneChain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fenceServiceClient) ReadAllChains(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ReadAllChainsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadAllChainsResponse)
	err := c.cc.Invoke(ctx, FenceService_ReadAllChains_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fenceServiceClient) UpdateOneChain(ctx context.Context, in *ChainRequest, opts ...grpc.CallOption) (*g_common.StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(g_common.StatusResponse)
	err := c.cc.Invoke(ctx, FenceService_UpdateOneChain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fenceServiceClient) DeleteOneChain(ctx context.Context, in *ChainRequest, opts ...grpc.CallOption) (*g_common.StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(g_common.StatusResponse)
	err := c.cc.Invoke(ctx, FenceService_DeleteOneChain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fenceServiceClient) CreateOneBoutique(ctx context.Context, in *BoutiqueRequest, opts ...grpc.CallOption) (*g_common.StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(g_common.StatusResponse)
	err := c.cc.Invoke(ctx, FenceService_CreateOneBoutique_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fenceServiceClient) ReadOneBoutique(ctx context.Context, in *BoutiqueRequest, opts ...grpc.CallOption) (*BoutiqueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoutiqueResponse)
	err := c.cc.Invoke(ctx, FenceService_ReadOneBoutique_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fenceServiceClient) UpdateOneBoutique(ctx context.Context, in *BoutiqueRequest, opts ...grpc.CallOption) (*g_common.StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(g_common.StatusResponse)
	err := c.cc.Invoke(ctx, FenceService_UpdateOneBoutique_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fenceServiceClient) DeleteOneBoutique(ctx context.Context, in *BoutiqueRequest, opts ...grpc.CallOption) (*g_common.StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(g_common.StatusResponse)
	err := c.cc.Invoke(ctx, FenceService_DeleteOneBoutique_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fenceServiceClient) RestoreOneBoutique(ctx context.Context, in *BoutiqueRequest, opts ...grpc.CallOption) (*g_common.StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(g_common.StatusResponse)
	err := c.cc.Invoke(ctx, FenceService_RestoreOneBoutique_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fenceServiceClient) ReadAllBoutiques(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ReadAllBoutiquesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadAllBoutiquesResponse)
	err := c.cc.Invoke(ctx, FenceService_ReadAllBoutiques_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fenceServiceClient) IsADeviceInChain(ctx context.Context, in *ReadDevicesRequest, opts ...grpc.CallOption) (*IsADeviceInChainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsADeviceInChainResponse)
	err := c.cc.Invoke(ctx, FenceService_IsADeviceInChain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fenceServiceClient) ReadDevices(ctx context.Context, in *ReadDevicesRequest, opts ...grpc.CallOption) (*device.Devices, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(device.Devices)
	err := c.cc.Invoke(ctx, FenceService_ReadDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fenceServiceClient) GenerateCodeForPairingDevice(ctx context.Context, in *chained_ids.ChainIdAndboutiqueId, opts ...grpc.CallOption) (*CodeForPairingDevice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CodeForPairingDevice)
	err := c.cc.Invoke(ctx, FenceService_GenerateCodeForPairingDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fenceServiceClient) ReadOnePendingDevice(ctx context.Context, in *ReadDeviceBtqRequest, opts ...grpc.CallOption) (*device.Device, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(device.Device)
	err := c.cc.Invoke(ctx, FenceService_ReadOnePendingDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fenceServiceClient) CreateDevice(ctx context.Context, in *PendingDeviceRequest, opts ...grpc.CallOption) (*CreateDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDeviceResponse)
	err := c.cc.Invoke(ctx, FenceService_CreateDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fenceServiceClient) UpdateDevicePassword(ctx context.Context, in *UpdateDevicePasswordRequest, opts ...grpc.CallOption) (*g_common.StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(g_common.StatusResponse)
	err := c.cc.Invoke(ctx, FenceService_UpdateDevicePassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fenceServiceClient) DeleteOneDevice(ctx context.Context, in *DeleteDeviceRequest, opts ...grpc.CallOption) (*g_common.StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(g_common.StatusResponse)
	err := c.cc.Invoke(ctx, FenceService_DeleteOneDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FenceServiceServer is the server API for FenceService service.
// All implementations must embed UnimplementedFenceServiceServer
// for forward compatibility.
//
// / boutiques & users
type FenceServiceServer interface {
	// / Health check with version information
	HealthCheck(context.Context, *empty.Empty) (*HealthCheckWeebiResponse, error)
	SignUp(context.Context, *user.SignUpRequest) (*user.SignUpResponse, error)
	AuthenticateWithCredentials(context.Context, *Credentials) (*Tokens, error)
	AuthenticateWithRefreshToken(context.Context, *RefreshToken) (*Tokens, error)
	// / Web session logout - invalidates session server-side. Envoy clears the cookie on success.
	Logout(context.Context, *empty.Empty) (*empty.Empty, error)
	// Password reset functionality
	RequestPasswordReset(context.Context, *PasswordResetRequest) (*g_common.StatusResponse, error)
	ConfirmPasswordReset(context.Context, *PasswordResetConfirmRequest) (*g_common.StatusResponse, error)
	// / only one firm per 'company'
	// / 1. user signup and get a userId & create firm permission
	// / 2. A. user create a firm
	// / Chain and Boutique will be created by default and will use the same firmId
	// / Since createFirm also updates user permission, clientApp needs to reauthent using refresh right after
	// / 2. B. user joins a firm is a different use case detailed in createPendingUser rpc
	CreateFirm(context.Context, *firm.CreateFirmRequest) (*firm.CreateFirmResponse, error)
	ReadOneFirm(context.Context, *empty.Empty) (*firm.Firm, error)
	CreatePendingUser(context.Context, *user.PendingUserRequest) (*user.PendingUserResponse, error)
	ReadOneUser(context.Context, *UserId) (*ReadOneUserResponse, error)
	// / Presumably, until 2030 firms will have max 9 users, why bother filter ?
	ReadAllUsers(context.Context, *empty.Empty) (*UsersPublic, error)
	// real update, not an upsert, does nothing if user not found
	UpdateOneUser(context.Context, *user.UserPublic) (*g_common.StatusResponse, error)
	UpdateUserPassword(context.Context, *PasswordUpdateRequest) (*g_common.StatusResponse, error)
	DeleteOneUser(context.Context, *UserId) (*g_common.StatusResponse, error)
	// Email verification - marks a user's email as verified
	MarkEmailVerified(context.Context, *MarkEmailVerifiedRequest) (*g_common.StatusResponse, error)
	// Update subscriber ID - links a user to a newsletter subscriber
	UpdateSubscriberId(context.Context, *UpdateSubscriberIdRequest) (*g_common.StatusResponse, error)
	CreateOneChain(context.Context, *btq_chain.Chain) (*g_common.StatusResponse, error)
	ReadAllChains(context.Context, *empty.Empty) (*ReadAllChainsResponse, error)
	// only update fiels not boutiques, not upsert, do nothing if unfound
	UpdateOneChain(context.Context, *ChainRequest) (*g_common.StatusResponse, error)
	// / hard/complete delete
	DeleteOneChain(context.Context, *ChainRequest) (*g_common.StatusResponse, error)
	CreateOneBoutique(context.Context, *BoutiqueRequest) (*g_common.StatusResponse, error)
	ReadOneBoutique(context.Context, *BoutiqueRequest) (*BoutiqueResponse, error)
	// / real update, not upsert, do nothing if unfound
	UpdateOneBoutique(context.Context, *BoutiqueRequest) (*g_common.StatusResponse, error)
	// / soft delete - marks boutique as deleted
	DeleteOneBoutique(context.Context, *BoutiqueRequest) (*g_common.StatusResponse, error)
	// / restore a soft-deleted boutique
	RestoreOneBoutique(context.Context, *BoutiqueRequest) (*g_common.StatusResponse, error)
	// / returns all active boutiques across all chains (filters out deleted ones)
	ReadAllBoutiques(context.Context, *empty.Empty) (*ReadAllBoutiquesResponse, error)
	// / scans all firm's devices, disregarding user rights
	// / used both in :
	// / weebi_app signups to REQUIRE that user pushes device data
	// / weebi_app device linking to PREVENT user from pushing data, pulling only
	// will be false by default, which is safer since it avoids corrupting data when linking new device that potentially weebi_app with different data
	// == isOneDevice at least
	IsADeviceInChain(context.Context, *ReadDevicesRequest) (*IsADeviceInChainResponse, error)
	// / return only device visible according to user rights
	ReadDevices(context.Context, *ReadDevicesRequest) (*device.Devices, error)
	// / device enrolment follows a different process than user enrolment
	// / generateCodeForPairingDevice is called by web app, it includes chainId and boutiqueId
	// / A device belongs to a boutique
	// TODO rename this create
	GenerateCodeForPairingDevice(context.Context, *chained_ids.ChainIdAndboutiqueId) (*CodeForPairingDevice, error)
	// / webapp listens to deviceStream awaiting PoS app to createDevice by typing the code
	ReadOnePendingDevice(context.Context, *ReadDeviceBtqRequest) (*device.Device, error)
	// / createDevice is called by mobile/desktop app
	// / await lasts for 2 minutes (to be tested)
	// / remove pending
	CreateDevice(context.Context, *PendingDeviceRequest) (*CreateDeviceResponse, error)
	// / removed as it brings a security risk
	// / rpc authenticateWithDevice (DeviceCredentials) returns (Tokens);
	UpdateDevicePassword(context.Context, *UpdateDevicePasswordRequest) (*g_common.StatusResponse, error)
	// / hard/forever delete
	DeleteOneDevice(context.Context, *DeleteDeviceRequest) (*g_common.StatusResponse, error)
	mustEmbedUnimplementedFenceServiceServer()
}

// UnimplementedFenceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFenceServiceServer struct{}

func (UnimplementedFenceServiceServer) HealthCheck(context.Context, *empty.Empty) (*HealthCheckWeebiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedFenceServiceServer) SignUp(context.Context, *user.SignUpRequest) (*user.SignUpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignUp not implemented")
}
func (UnimplementedFenceServiceServer) AuthenticateWithCredentials(context.Context, *Credentials) (*Tokens, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthenticateWithCredentials not implemented")
}
func (UnimplementedFenceServiceServer) AuthenticateWithRefreshToken(context.Context, *RefreshToken) (*Tokens, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthenticateWithRefreshToken not implemented")
}
func (UnimplementedFenceServiceServer) Logout(context.Context, *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedFenceServiceServer) RequestPasswordReset(context.Context, *PasswordResetRequest) (*g_common.StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestPasswordReset not implemented")
}
func (UnimplementedFenceServiceServer) ConfirmPasswordReset(context.Context, *PasswordResetConfirmRequest) (*g_common.StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmPasswordReset not implemented")
}
func (UnimplementedFenceServiceServer) CreateFirm(context.Context, *firm.CreateFirmRequest) (*firm.CreateFirmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFirm not implemented")
}
func (UnimplementedFenceServiceServer) ReadOneFirm(context.Context, *empty.Empty) (*firm.Firm, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadOneFirm not implemented")
}
func (UnimplementedFenceServiceServer) CreatePendingUser(context.Context, *user.PendingUserRequest) (*user.PendingUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePendingUser not implemented")
}
func (UnimplementedFenceServiceServer) ReadOneUser(context.Context, *UserId) (*ReadOneUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadOneUser not implemented")
}
func (UnimplementedFenceServiceServer) ReadAllUsers(context.Context, *empty.Empty) (*UsersPublic, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadAllUsers not implemented")
}
func (UnimplementedFenceServiceServer) UpdateOneUser(context.Context, *user.UserPublic) (*g_common.StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOneUser not implemented")
}
func (UnimplementedFenceServiceServer) UpdateUserPassword(context.Context, *PasswordUpdateRequest) (*g_common.StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserPassword not implemented")
}
func (UnimplementedFenceServiceServer) DeleteOneUser(context.Context, *UserId) (*g_common.StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteOneUser not implemented")
}
func (UnimplementedFenceServiceServer) MarkEmailVerified(context.Context, *MarkEmailVerifiedRequest) (*g_common.StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkEmailVerified not implemented")
}
func (UnimplementedFenceServiceServer) UpdateSubscriberId(context.Context, *UpdateSubscriberIdRequest) (*g_common.StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSubscriberId not implemented")
}
func (UnimplementedFenceServiceServer) CreateOneChain(context.Context, *btq_chain.Chain) (*g_common.StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOneChain not implemented")
}
func (UnimplementedFenceServiceServer) ReadAllChains(context.Context, *empty.Empty) (*ReadAllChainsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadAllChains not implemented")
}
func (UnimplementedFenceServiceServer) UpdateOneChain(context.Context, *ChainRequest) (*g_common.StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOneChain not implemented")
}
func (UnimplementedFenceServiceServer) DeleteOneChain(context.Context, *ChainRequest) (*g_common.StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteOneChain not implemented")
}
func (UnimplementedFenceServiceServer) CreateOneBoutique(context.Context, *BoutiqueRequest) (*g_common.StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOneBoutique not implemented")
}
func (UnimplementedFenceServiceServer) ReadOneBoutique(context.Context, *BoutiqueRequest) (*BoutiqueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadOneBoutique not implemented")
}
func (UnimplementedFenceServiceServer) UpdateOneBoutique(context.Context, *BoutiqueRequest) (*g_common.StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOneBoutique not implemented")
}
func (UnimplementedFenceServiceServer) DeleteOneBoutique(context.Context, *BoutiqueRequest) (*g_common.StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteOneBoutique not implemented")
}
func (UnimplementedFenceServiceServer) RestoreOneBoutique(context.Context, *BoutiqueRequest) (*g_common.StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestoreOneBoutique not implemented")
}
func (UnimplementedFenceServiceServer) ReadAllBoutiques(context.Context, *empty.Empty) (*ReadAllBoutiquesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadAllBoutiques not implemented")
}
func (UnimplementedFenceServiceServer) IsADeviceInChain(context.Context, *ReadDevicesRequest) (*IsADeviceInChainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsADeviceInChain not implemented")
}
func (UnimplementedFenceServiceServer) ReadDevices(context.Context, *ReadDevicesRequest) (*device.Devices, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadDevices not implemented")
}
func (UnimplementedFenceServiceServer) GenerateCodeForPairingDevice(context.Context, *chained_ids.ChainIdAndboutiqueId) (*CodeForPairingDevice, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateCodeForPairingDevice not implemented")
}
func (UnimplementedFenceServiceServer) ReadOnePendingDevice(context.Context, *ReadDeviceBtqRequest) (*device.Device, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadOnePendingDevice not implemented")
}
func (UnimplementedFenceServiceServer) CreateDevice(context.Context, *PendingDeviceRequest) (*CreateDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDevice not implemented")
}
func (UnimplementedFenceServiceServer) UpdateDevicePassword(context.Context, *UpdateDevicePasswordRequest) (*g_common.StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDevicePassword not implemented")
}
func (UnimplementedFenceServiceServer) DeleteOneDevice(context.Context, *DeleteDeviceRequest) (*g_common.StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteOneDevice not implemented")
}
func (UnimplementedFenceServiceServer) mustEmbedUnimplementedFenceServiceServer() {}
func (UnimplementedFenceServiceServer) testEmbeddedByValue()                      {}

// UnsafeFenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FenceServiceServer will
// result in compilation errors.
type UnsafeFenceServiceServer interface {
	mustEmbedUnimplementedFenceServiceServer()
}

func RegisterFenceServiceServer(s grpc.ServiceRegistrar, srv FenceServiceServer) {
	// If the following call pancis, it indicates UnimplementedFenceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FenceService_ServiceDesc, srv)
}

func _FenceService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FenceServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FenceService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FenceServiceServer).HealthCheck(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _FenceService_SignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(user.SignUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FenceServiceServer).SignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FenceService_SignUp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FenceServiceServer).SignUp(ctx, req.(*user.SignUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FenceService_AuthenticateWithCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Credentials)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FenceServiceServer).AuthenticateWithCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FenceService_AuthenticateWithCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FenceServiceServer).AuthenticateWithCredentials(ctx, req.(*Credentials))
	}
	return interceptor(ctx, in, info, handler)
}

func _FenceService_AuthenticateWithRefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FenceServiceServer).AuthenticateWithRefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FenceService_AuthenticateWithRefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FenceServiceServer).AuthenticateWithRefreshToken(ctx, req.(*RefreshToken))
	}
	return interceptor(ctx, in, info, handler)
}

func _FenceService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FenceServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FenceService_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FenceServiceServer).Logout(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _FenceService_RequestPasswordReset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasswordResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FenceServiceServer).RequestPasswordReset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FenceService_RequestPasswordReset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FenceServiceServer).RequestPasswordReset(ctx, req.(*PasswordResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FenceService_ConfirmPasswordReset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasswordResetConfirmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FenceServiceServer).ConfirmPasswordReset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FenceService_ConfirmPasswordReset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FenceServiceServer).ConfirmPasswordReset(ctx, req.(*PasswordResetConfirmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FenceService_CreateFirm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(firm.CreateFirmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FenceServiceServer).CreateFirm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FenceService_CreateFirm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FenceServiceServer).CreateFirm(ctx, req.(*firm.CreateFirmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FenceService_ReadOneFirm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FenceServiceServer).ReadOneFirm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FenceService_ReadOneFirm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FenceServiceServer).ReadOneFirm(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _FenceService_CreatePendingUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(user.PendingUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FenceServiceServer).CreatePendingUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FenceService_CreatePendingUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FenceServiceServer).CreatePendingUser(ctx, req.(*user.PendingUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FenceService_ReadOneUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FenceServiceServer).ReadOneUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FenceService_ReadOneUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FenceServiceServer).ReadOneUser(ctx, req.(*UserId))
	}
	return interceptor(ctx, in, info, handler)
}

func _FenceService_ReadAllUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FenceServiceServer).ReadAllUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FenceService_ReadAllUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FenceServiceServer).ReadAllUsers(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _FenceService_UpdateOneUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(user.UserPublic)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FenceServiceServer).UpdateOneUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FenceService_UpdateOneUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FenceServiceServer).UpdateOneUser(ctx, req.(*user.UserPublic))
	}
	return interceptor(ctx, in, info, handler)
}

func _FenceService_UpdateUserPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasswordUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FenceServiceServer).UpdateUserPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FenceService_UpdateUserPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FenceServiceServer).UpdateUserPassword(ctx, req.(*PasswordUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FenceService_DeleteOneUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FenceServiceServer).DeleteOneUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FenceService_DeleteOneUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FenceServiceServer).DeleteOneUser(ctx, req.(*UserId))
	}
	return interceptor(ctx, in, info, handler)
}

func _FenceService_MarkEmailVerified_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkEmailVerifiedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FenceServiceServer).MarkEmailVerified(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FenceService_MarkEmailVerified_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FenceServiceServer).MarkEmailVerified(ctx, req.(*MarkEmailVerifiedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FenceService_UpdateSubscriberId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSubscriberIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FenceServiceServer).UpdateSubscriberId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FenceService_UpdateSubscriberId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FenceServiceServer).UpdateSubscriberId(ctx, req.(*UpdateSubscriberIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FenceService_CreateOneChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(btq_chain.Chain)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FenceServiceServer).CreateOneChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FenceService_CreateOneChain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FenceServiceServer).CreateOneChain(ctx, req.(*btq_chain.Chain))
	}
	return interceptor(ctx, in, info, handler)
}

func _FenceService_ReadAllChains_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FenceServiceServer).ReadAllChains(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FenceService_ReadAllChains_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FenceServiceServer).ReadAllChains(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _FenceService_UpdateOneChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FenceServiceServer).UpdateOneChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FenceService_UpdateOneChain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FenceServiceServer).UpdateOneChain(ctx, req.(*ChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FenceService_DeleteOneChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FenceServiceServer).DeleteOneChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FenceService_DeleteOneChain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FenceServiceServer).DeleteOneChain(ctx, req.(*ChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FenceService_CreateOneBoutique_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BoutiqueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FenceServiceServer).CreateOneBoutique(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FenceService_CreateOneBoutique_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FenceServiceServer).CreateOneBoutique(ctx, req.(*BoutiqueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FenceService_ReadOneBoutique_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BoutiqueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FenceServiceServer).ReadOneBoutique(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FenceService_ReadOneBoutique_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FenceServiceServer).ReadOneBoutique(ctx, req.(*BoutiqueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FenceService_UpdateOneBoutique_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BoutiqueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FenceServiceServer).UpdateOneBoutique(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FenceService_UpdateOneBoutique_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FenceServiceServer).UpdateOneBoutique(ctx, req.(*BoutiqueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FenceService_DeleteOneBoutique_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BoutiqueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FenceServiceServer).DeleteOneBoutique(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FenceService_DeleteOneBoutique_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FenceServiceServer).DeleteOneBoutique(ctx, req.(*BoutiqueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FenceService_RestoreOneBoutique_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BoutiqueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FenceServiceServer).RestoreOneBoutique(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FenceService_RestoreOneBoutique_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FenceServiceServer).RestoreOneBoutique(ctx, req.(*BoutiqueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FenceService_ReadAllBoutiques_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FenceServiceServer).ReadAllBoutiques(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FenceService_ReadAllBoutiques_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FenceServiceServer).ReadAllBoutiques(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _FenceService_IsADeviceInChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FenceServiceServer).IsADeviceInChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FenceService_IsADeviceInChain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FenceServiceServer).IsADeviceInChain(ctx, req.(*ReadDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FenceService_ReadDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FenceServiceServer).ReadDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FenceService_ReadDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FenceServiceServer).ReadDevices(ctx, req.(*ReadDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FenceService_GenerateCodeForPairingDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(chained_ids.ChainIdAndboutiqueId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FenceServiceServer).GenerateCodeForPairingDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FenceService_GenerateCodeForPairingDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FenceServiceServer).GenerateCodeForPairingDevice(ctx, req.(*chained_ids.ChainIdAndboutiqueId))
	}
	return interceptor(ctx, in, info, handler)
}

func _FenceService_ReadOnePendingDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadDeviceBtqRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FenceServiceServer).ReadOnePendingDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FenceService_ReadOnePendingDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FenceServiceServer).ReadOnePendingDevice(ctx, req.(*ReadDeviceBtqRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FenceService_CreateDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PendingDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FenceServiceServer).CreateDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FenceService_CreateDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FenceServiceServer).CreateDevice(ctx, req.(*PendingDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FenceService_UpdateDevicePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDevicePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FenceServiceServer).UpdateDevicePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FenceService_UpdateDevicePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FenceServiceServer).UpdateDevicePassword(ctx, req.(*UpdateDevicePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FenceService_DeleteOneDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FenceServiceServer).DeleteOneDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FenceService_DeleteOneDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FenceServiceServer).DeleteOneDevice(ctx, req.(*DeleteDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FenceService_ServiceDesc is the grpc.ServiceDesc for FenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weebi.fence.service.FenceService",
	HandlerType: (*FenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "healthCheck",
			Handler:    _FenceService_HealthCheck_Handler,
		},
		{
			MethodName: "signUp",
			Handler:    _FenceService_SignUp_Handler,
		},
		{
			MethodName: "authenticateWithCredentials",
			Handler:    _FenceService_AuthenticateWithCredentials_Handler,
		},
		{
			MethodName: "authenticateWithRefreshToken",
			Handler:    _FenceService_AuthenticateWithRefreshToken_Handler,
		},
		{
			MethodName: "logout",
			Handler:    _FenceService_Logout_Handler,
		},
		{
			MethodName: "requestPasswordReset",
			Handler:    _FenceService_RequestPasswordReset_Handler,
		},
		{
			MethodName: "confirmPasswordReset",
			Handler:    _FenceService_ConfirmPasswordReset_Handler,
		},
		{
			MethodName: "createFirm",
			Handler:    _FenceService_CreateFirm_Handler,
		},
		{
			MethodName: "readOneFirm",
			Handler:    _FenceService_ReadOneFirm_Handler,
		},
		{
			MethodName: "createPendingUser",
			Handler:    _FenceService_CreatePendingUser_Handler,
		},
		{
			MethodName: "readOneUser",
			Handler:    _FenceService_ReadOneUser_Handler,
		},
		{
			MethodName: "readAllUsers",
			Handler:    _FenceService_ReadAllUsers_Handler,
		},
		{
			MethodName: "updateOneUser",
			Handler:    _FenceService_UpdateOneUser_Handler,
		},
		{
			MethodName: "updateUserPassword",
			Handler:    _FenceService_UpdateUserPassword_Handler,
		},
		{
			MethodName: "deleteOneUser",
			Handler:    _FenceService_DeleteOneUser_Handler,
		},
		{
			MethodName: "markEmailVerified",
			Handler:    _FenceService_MarkEmailVerified_Handler,
		},
		{
			MethodName: "updateSubscriberId",
			Handler:    _FenceService_UpdateSubscriberId_Handler,
		},
		{
			MethodName: "createOneChain",
			Handler:    _FenceService_CreateOneChain_Handler,
		},
		{
			MethodName: "readAllChains",
			Handler:    _FenceService_ReadAllChains_Handler,
		},
		{
			MethodName: "updateOneChain",
			Handler:    _FenceService_UpdateOneChain_Handler,
		},
		{
			MethodName: "deleteOneChain",
			Handler:    _FenceService_DeleteOneChain_Handler,
		},
		{
			MethodName: "createOneBoutique",
			Handler:    _FenceService_CreateOneBoutique_Handler,
		},
		{
			MethodName: "readOneBoutique",
			Handler:    _FenceService_ReadOneBoutique_Handler,
		},
		{
			MethodName: "updateOneBoutique",
			Handler:    _FenceService_UpdateOneBoutique_Handler,
		},
		{
			MethodName: "deleteOneBoutique",
			Handler:    _FenceService_DeleteOneBoutique_Handler,
		},
		{
			MethodName: "restoreOneBoutique",
			Handler:    _FenceService_RestoreOneBoutique_Handler,
		},
		{
			MethodName: "readAllBoutiques",
			Handler:    _FenceService_ReadAllBoutiques_Handler,
		},
		{
			MethodName: "isADeviceInChain",
			Handler:    _FenceService_IsADeviceInChain_Handler,
		},
		{
			MethodName: "readDevices",
			Handler:    _FenceService_ReadDevices_Handler,
		},
		{
			MethodName: "generateCodeForPairingDevice",
			Handler:    _FenceService_GenerateCodeForPairingDevice_Handler,
		},
		{
			MethodName: "readOnePendingDevice",
			Handler:    _FenceService_ReadOnePendingDevice_Handler,
		},
		{
			MethodName: "createDevice",
			Handler:    _FenceService_CreateDevice_Handler,
		},
		{
			MethodName: "updateDevicePassword",
			Handler:    _FenceService_UpdateDevicePassword_Handler,
		},
		{
			MethodName: "deleteOneDevice",
			Handler:    _FenceService_DeleteOneDevice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fence_service.proto",
}
