// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: fence_service.proto

package service

import (
	boutique "github.com/weebi-com/protos/boutique"
	btq_chain "github.com/weebi-com/protos/btq_chain"
	chained_ids "github.com/weebi-com/protos/common/chained_ids"
	empty "github.com/weebi-com/protos/common/empty"
	g_common "github.com/weebi-com/protos/common/g_common"
	device "github.com/weebi-com/protos/device"
	firm "github.com/weebi-com/protos/firm"
	user "github.com/weebi-com/protos/user"
	user_permissions "github.com/weebi-com/protos/user_permissions"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// /
type ChainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       string                 `protobuf:"bytes,1,opt,name=chainId,proto3" json:"chainId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainRequest) Reset() {
	*x = ChainRequest{}
	mi := &file_fence_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainRequest) ProtoMessage() {}

func (x *ChainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fence_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainRequest.ProtoReflect.Descriptor instead.
func (*ChainRequest) Descriptor() ([]byte, []int) {
	return file_fence_service_proto_rawDescGZIP(), []int{0}
}

func (x *ChainRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *ChainRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// / one boutique creation the server will assign the boutiqueId
type BoutiqueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       string                 `protobuf:"bytes,1,opt,name=chainId,proto3" json:"chainId,omitempty"`
	Boutique      *boutique.BoutiquePb   `protobuf:"bytes,2,opt,name=boutique,proto3" json:"boutique,omitempty"`
	Logo          []byte                 `protobuf:"bytes,3,opt,name=logo,proto3" json:"logo,omitempty"`
	LogoExtension string                 `protobuf:"bytes,4,opt,name=logoExtension,proto3" json:"logoExtension,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoutiqueRequest) Reset() {
	*x = BoutiqueRequest{}
	mi := &file_fence_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoutiqueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoutiqueRequest) ProtoMessage() {}

func (x *BoutiqueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fence_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoutiqueRequest.ProtoReflect.Descriptor instead.
func (*BoutiqueRequest) Descriptor() ([]byte, []int) {
	return file_fence_service_proto_rawDescGZIP(), []int{1}
}

func (x *BoutiqueRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *BoutiqueRequest) GetBoutique() *boutique.BoutiquePb {
	if x != nil {
		return x.Boutique
	}
	return nil
}

func (x *BoutiqueRequest) GetLogo() []byte {
	if x != nil {
		return x.Logo
	}
	return nil
}

func (x *BoutiqueRequest) GetLogoExtension() string {
	if x != nil {
		return x.LogoExtension
	}
	return ""
}

// / one boutique creation the server will assign the boutiqueId
type BoutiqueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Boutique      *boutique.BoutiquePb   `protobuf:"bytes,1,opt,name=boutique,proto3" json:"boutique,omitempty"`
	Logo          []byte                 `protobuf:"bytes,2,opt,name=logo,proto3" json:"logo,omitempty"`
	LogoExtension string                 `protobuf:"bytes,3,opt,name=logoExtension,proto3" json:"logoExtension,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoutiqueResponse) Reset() {
	*x = BoutiqueResponse{}
	mi := &file_fence_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoutiqueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoutiqueResponse) ProtoMessage() {}

func (x *BoutiqueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fence_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoutiqueResponse.ProtoReflect.Descriptor instead.
func (*BoutiqueResponse) Descriptor() ([]byte, []int) {
	return file_fence_service_proto_rawDescGZIP(), []int{2}
}

func (x *BoutiqueResponse) GetBoutique() *boutique.BoutiquePb {
	if x != nil {
		return x.Boutique
	}
	return nil
}

func (x *BoutiqueResponse) GetLogo() []byte {
	if x != nil {
		return x.Logo
	}
	return nil
}

func (x *BoutiqueResponse) GetLogoExtension() string {
	if x != nil {
		return x.LogoExtension
	}
	return ""
}

// / deviceId == userId, so front can reuse deviceId to try login in
// / remove pending
type CreateDeviceResponse struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	StatusResponse *g_common.StatusResponse `protobuf:"bytes,1,opt,name=statusResponse,proto3" json:"statusResponse,omitempty"`
	FirmId         string                   `protobuf:"bytes,2,opt,name=firmId,proto3" json:"firmId,omitempty"`
	ChainId        string                   `protobuf:"bytes,3,opt,name=chainId,proto3" json:"chainId,omitempty"`
	BoutiqueId     string                   `protobuf:"bytes,4,opt,name=boutiqueId,proto3" json:"boutiqueId,omitempty"`
	DeviceId       string                   `protobuf:"bytes,5,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateDeviceResponse) Reset() {
	*x = CreateDeviceResponse{}
	mi := &file_fence_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeviceResponse) ProtoMessage() {}

func (x *CreateDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fence_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeviceResponse.ProtoReflect.Descriptor instead.
func (*CreateDeviceResponse) Descriptor() ([]byte, []int) {
	return file_fence_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateDeviceResponse) GetStatusResponse() *g_common.StatusResponse {
	if x != nil {
		return x.StatusResponse
	}
	return nil
}

func (x *CreateDeviceResponse) GetFirmId() string {
	if x != nil {
		return x.FirmId
	}
	return ""
}

func (x *CreateDeviceResponse) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *CreateDeviceResponse) GetBoutiqueId() string {
	if x != nil {
		return x.BoutiqueId
	}
	return ""
}

func (x *CreateDeviceResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type ReadOneUserResponse struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	StatusResponse *g_common.StatusResponse `protobuf:"bytes,1,opt,name=statusResponse,proto3" json:"statusResponse,omitempty"`
	User           *user.UserPublic         `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReadOneUserResponse) Reset() {
	*x = ReadOneUserResponse{}
	mi := &file_fence_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadOneUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadOneUserResponse) ProtoMessage() {}

func (x *ReadOneUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fence_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadOneUserResponse.ProtoReflect.Descriptor instead.
func (*ReadOneUserResponse) Descriptor() ([]byte, []int) {
	return file_fence_service_proto_rawDescGZIP(), []int{4}
}

func (x *ReadOneUserResponse) GetStatusResponse() *g_common.StatusResponse {
	if x != nil {
		return x.StatusResponse
	}
	return nil
}

func (x *ReadOneUserResponse) GetUser() *user.UserPublic {
	if x != nil {
		return x.User
	}
	return nil
}

type UsersPublic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*user.UserPublic     `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersPublic) Reset() {
	*x = UsersPublic{}
	mi := &file_fence_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersPublic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersPublic) ProtoMessage() {}

func (x *UsersPublic) ProtoReflect() protoreflect.Message {
	mi := &file_fence_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersPublic.ProtoReflect.Descriptor instead.
func (*UsersPublic) Descriptor() ([]byte, []int) {
	return file_fence_service_proto_rawDescGZIP(), []int{5}
}

func (x *UsersPublic) GetUsers() []*user.UserPublic {
	if x != nil {
		return x.Users
	}
	return nil
}

type ReadAllChainsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// google.retail.common.StatusResponse ?
	// Note: chains contain only active boutiques (deleted ones are filtered out)
	Chains        []*btq_chain.Chain `protobuf:"bytes,1,rep,name=chains,proto3" json:"chains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAllChainsResponse) Reset() {
	*x = ReadAllChainsResponse{}
	mi := &file_fence_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllChainsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllChainsResponse) ProtoMessage() {}

func (x *ReadAllChainsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fence_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllChainsResponse.ProtoReflect.Descriptor instead.
func (*ReadAllChainsResponse) Descriptor() ([]byte, []int) {
	return file_fence_service_proto_rawDescGZIP(), []int{6}
}

func (x *ReadAllChainsResponse) GetChains() []*btq_chain.Chain {
	if x != nil {
		return x.Chains
	}
	return nil
}

type ReadAllBoutiquesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Boutiques     []*boutique.BoutiquePb `protobuf:"bytes,1,rep,name=boutiques,proto3" json:"boutiques,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAllBoutiquesResponse) Reset() {
	*x = ReadAllBoutiquesResponse{}
	mi := &file_fence_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllBoutiquesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllBoutiquesResponse) ProtoMessage() {}

func (x *ReadAllBoutiquesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fence_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllBoutiquesResponse.ProtoReflect.Descriptor instead.
func (*ReadAllBoutiquesResponse) Descriptor() ([]byte, []int) {
	return file_fence_service_proto_rawDescGZIP(), []int{7}
}

func (x *ReadAllBoutiquesResponse) GetBoutiques() []*boutique.BoutiquePb {
	if x != nil {
		return x.Boutiques
	}
	return nil
}

type ReadDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       string                 `protobuf:"bytes,1,opt,name=chainId,proto3" json:"chainId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadDevicesRequest) Reset() {
	*x = ReadDevicesRequest{}
	mi := &file_fence_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDevicesRequest) ProtoMessage() {}

func (x *ReadDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fence_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDevicesRequest.ProtoReflect.Descriptor instead.
func (*ReadDevicesRequest) Descriptor() ([]byte, []int) {
	return file_fence_service_proto_rawDescGZIP(), []int{8}
}

func (x *ReadDevicesRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

type IsADeviceInChainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsADevice     bool                   `protobuf:"varint,1,opt,name=isADevice,proto3" json:"isADevice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsADeviceInChainResponse) Reset() {
	*x = IsADeviceInChainResponse{}
	mi := &file_fence_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsADeviceInChainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsADeviceInChainResponse) ProtoMessage() {}

func (x *IsADeviceInChainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fence_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsADeviceInChainResponse.ProtoReflect.Descriptor instead.
func (*IsADeviceInChainResponse) Descriptor() ([]byte, []int) {
	return file_fence_service_proto_rawDescGZIP(), []int{9}
}

func (x *IsADeviceInChainResponse) GetIsADevice() bool {
	if x != nil {
		return x.IsADevice
	}
	return false
}

type ReadDeviceBtqRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       string                 `protobuf:"bytes,1,opt,name=chainId,proto3" json:"chainId,omitempty"`
	BoutiqueId    string                 `protobuf:"bytes,2,opt,name=boutiqueId,proto3" json:"boutiqueId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadDeviceBtqRequest) Reset() {
	*x = ReadDeviceBtqRequest{}
	mi := &file_fence_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadDeviceBtqRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDeviceBtqRequest) ProtoMessage() {}

func (x *ReadDeviceBtqRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fence_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDeviceBtqRequest.ProtoReflect.Descriptor instead.
func (*ReadDeviceBtqRequest) Descriptor() ([]byte, []int) {
	return file_fence_service_proto_rawDescGZIP(), []int{10}
}

func (x *ReadDeviceBtqRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *ReadDeviceBtqRequest) GetBoutiqueId() string {
	if x != nil {
		return x.BoutiqueId
	}
	return ""
}

type DeleteDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       string                 `protobuf:"bytes,1,opt,name=chainId,proto3" json:"chainId,omitempty"`
	Device        *device.Device         `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDeviceRequest) Reset() {
	*x = DeleteDeviceRequest{}
	mi := &file_fence_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDeviceRequest) ProtoMessage() {}

func (x *DeleteDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fence_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDeviceRequest.ProtoReflect.Descriptor instead.
func (*DeleteDeviceRequest) Descriptor() ([]byte, []int) {
	return file_fence_service_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteDeviceRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *DeleteDeviceRequest) GetDevice() *device.Device {
	if x != nil {
		return x.Device
	}
	return nil
}

type MailAndEncyptedPassword struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Mail              string                 `protobuf:"bytes,1,opt,name=mail,proto3" json:"mail,omitempty"`
	PasswordEncrypted string                 `protobuf:"bytes,2,opt,name=passwordEncrypted,proto3" json:"passwordEncrypted,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MailAndEncyptedPassword) Reset() {
	*x = MailAndEncyptedPassword{}
	mi := &file_fence_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailAndEncyptedPassword) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailAndEncyptedPassword) ProtoMessage() {}

func (x *MailAndEncyptedPassword) ProtoReflect() protoreflect.Message {
	mi := &file_fence_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailAndEncyptedPassword.ProtoReflect.Descriptor instead.
func (*MailAndEncyptedPassword) Descriptor() ([]byte, []int) {
	return file_fence_service_proto_rawDescGZIP(), []int{12}
}

func (x *MailAndEncyptedPassword) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

func (x *MailAndEncyptedPassword) GetPasswordEncrypted() string {
	if x != nil {
		return x.PasswordEncrypted
	}
	return ""
}

type UserId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserId) Reset() {
	*x = UserId{}
	mi := &file_fence_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserId) ProtoMessage() {}

func (x *UserId) ProtoReflect() protoreflect.Message {
	mi := &file_fence_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserId.ProtoReflect.Descriptor instead.
func (*UserId) Descriptor() ([]byte, []int) {
	return file_fence_service_proto_rawDescGZIP(), []int{13}
}

func (x *UserId) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type Access struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	ChainIds      *user_permissions.ChainIds    `protobuf:"bytes,1,opt,name=chainIds,proto3" json:"chainIds,omitempty"`
	BoutiqueIds   *user_permissions.BoutiqueIds `protobuf:"bytes,2,opt,name=boutiqueIds,proto3" json:"boutiqueIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Access) Reset() {
	*x = Access{}
	mi := &file_fence_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Access) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Access) ProtoMessage() {}

func (x *Access) ProtoReflect() protoreflect.Message {
	mi := &file_fence_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Access.ProtoReflect.Descriptor instead.
func (*Access) Descriptor() ([]byte, []int) {
	return file_fence_service_proto_rawDescGZIP(), []int{14}
}

func (x *Access) GetChainIds() *user_permissions.ChainIds {
	if x != nil {
		return x.ChainIds
	}
	return nil
}

func (x *Access) GetBoutiqueIds() *user_permissions.BoutiqueIds {
	if x != nil {
		return x.BoutiqueIds
	}
	return nil
}

type Credentials struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mail          string                 `protobuf:"bytes,1,opt,name=mail,proto3" json:"mail,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	IsWebApp      bool                   `protobuf:"varint,3,opt,name=isWebApp,proto3" json:"isWebApp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credentials) Reset() {
	*x = Credentials{}
	mi := &file_fence_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credentials) ProtoMessage() {}

func (x *Credentials) ProtoReflect() protoreflect.Message {
	mi := &file_fence_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credentials.ProtoReflect.Descriptor instead.
func (*Credentials) Descriptor() ([]byte, []int) {
	return file_fence_service_proto_rawDescGZIP(), []int{15}
}

func (x *Credentials) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

func (x *Credentials) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Credentials) GetIsWebApp() bool {
	if x != nil {
		return x.IsWebApp
	}
	return false
}

type DeviceCredentials struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirmId        string                 `protobuf:"bytes,1,opt,name=firmId,proto3" json:"firmId,omitempty"`
	ChainId       string                 `protobuf:"bytes,2,opt,name=chainId,proto3" json:"chainId,omitempty"`
	BoutiqueId    string                 `protobuf:"bytes,3,opt,name=boutiqueId,proto3" json:"boutiqueId,omitempty"`
	DeviceId      string                 `protobuf:"bytes,4,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceCredentials) Reset() {
	*x = DeviceCredentials{}
	mi := &file_fence_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCredentials) ProtoMessage() {}

func (x *DeviceCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_fence_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCredentials.ProtoReflect.Descriptor instead.
func (*DeviceCredentials) Descriptor() ([]byte, []int) {
	return file_fence_service_proto_rawDescGZIP(), []int{16}
}

func (x *DeviceCredentials) GetFirmId() string {
	if x != nil {
		return x.FirmId
	}
	return ""
}

func (x *DeviceCredentials) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *DeviceCredentials) GetBoutiqueId() string {
	if x != nil {
		return x.BoutiqueId
	}
	return ""
}

func (x *DeviceCredentials) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceCredentials) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RefreshToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshToken) Reset() {
	*x = RefreshToken{}
	mi := &file_fence_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshToken) ProtoMessage() {}

func (x *RefreshToken) ProtoReflect() protoreflect.Message {
	mi := &file_fence_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshToken.ProtoReflect.Descriptor instead.
func (*RefreshToken) Descriptor() ([]byte, []int) {
	return file_fence_service_proto_rawDescGZIP(), []int{17}
}

func (x *RefreshToken) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type Tokens struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AccessToken        string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	RefreshToken       string                 `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	MustChangePassword bool                   `protobuf:"varint,3,opt,name=mustChangePassword,proto3" json:"mustChangePassword,omitempty"`
	SessionId          string                 `protobuf:"bytes,4,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Tokens) Reset() {
	*x = Tokens{}
	mi := &file_fence_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tokens) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tokens) ProtoMessage() {}

func (x *Tokens) ProtoReflect() protoreflect.Message {
	mi := &file_fence_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tokens.ProtoReflect.Descriptor instead.
func (*Tokens) Descriptor() ([]byte, []int) {
	return file_fence_service_proto_rawDescGZIP(), []int{18}
}

func (x *Tokens) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *Tokens) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *Tokens) GetMustChangePassword() bool {
	if x != nil {
		return x.MustChangePassword
	}
	return false
}

func (x *Tokens) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type UpdateDevicePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       string                 `protobuf:"bytes,1,opt,name=chainId,proto3" json:"chainId,omitempty"`
	Device        *device.Device         `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDevicePasswordRequest) Reset() {
	*x = UpdateDevicePasswordRequest{}
	mi := &file_fence_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDevicePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDevicePasswordRequest) ProtoMessage() {}

func (x *UpdateDevicePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fence_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDevicePasswordRequest.ProtoReflect.Descriptor instead.
func (*UpdateDevicePasswordRequest) Descriptor() ([]byte, []int) {
	return file_fence_service_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateDevicePasswordRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *UpdateDevicePasswordRequest) GetDevice() *device.Device {
	if x != nil {
		return x.Device
	}
	return nil
}

type PasswordUpdateRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	FirmId          string                 `protobuf:"bytes,2,opt,name=firmId,proto3" json:"firmId,omitempty"`
	PasswordCurrent string                 `protobuf:"bytes,3,opt,name=passwordCurrent,proto3" json:"passwordCurrent,omitempty"`
	PasswordNew     string                 `protobuf:"bytes,4,opt,name=passwordNew,proto3" json:"passwordNew,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PasswordUpdateRequest) Reset() {
	*x = PasswordUpdateRequest{}
	mi := &file_fence_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordUpdateRequest) ProtoMessage() {}

func (x *PasswordUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fence_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordUpdateRequest.ProtoReflect.Descriptor instead.
func (*PasswordUpdateRequest) Descriptor() ([]byte, []int) {
	return file_fence_service_proto_rawDescGZIP(), []int{20}
}

func (x *PasswordUpdateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PasswordUpdateRequest) GetFirmId() string {
	if x != nil {
		return x.FirmId
	}
	return ""
}

func (x *PasswordUpdateRequest) GetPasswordCurrent() string {
	if x != nil {
		return x.PasswordCurrent
	}
	return ""
}

func (x *PasswordUpdateRequest) GetPasswordNew() string {
	if x != nil {
		return x.PasswordNew
	}
	return ""
}

type PendingDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HardwareInfo  *device.HardwareInfo   `protobuf:"bytes,1,opt,name=hardwareInfo,proto3" json:"hardwareInfo,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingDeviceRequest) Reset() {
	*x = PendingDeviceRequest{}
	mi := &file_fence_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingDeviceRequest) ProtoMessage() {}

func (x *PendingDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fence_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingDeviceRequest.ProtoReflect.Descriptor instead.
func (*PendingDeviceRequest) Descriptor() ([]byte, []int) {
	return file_fence_service_proto_rawDescGZIP(), []int{21}
}

func (x *PendingDeviceRequest) GetHardwareInfo() *device.HardwareInfo {
	if x != nil {
		return x.HardwareInfo
	}
	return nil
}

func (x *PendingDeviceRequest) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type CodeForPairingDevice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirmId        string                 `protobuf:"bytes,1,opt,name=firmId,proto3" json:"firmId,omitempty"`
	ChainId       string                 `protobuf:"bytes,2,opt,name=chainId,proto3" json:"chainId,omitempty"`
	BoutiqueId    string                 `protobuf:"bytes,3,opt,name=boutiqueId,proto3" json:"boutiqueId,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=userId,proto3" json:"userId,omitempty"`
	Code          int32                  `protobuf:"varint,5,opt,name=code,proto3" json:"code,omitempty"`
	TimestampUTC  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestampUTC,proto3" json:"timestampUTC,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CodeForPairingDevice) Reset() {
	*x = CodeForPairingDevice{}
	mi := &file_fence_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeForPairingDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeForPairingDevice) ProtoMessage() {}

func (x *CodeForPairingDevice) ProtoReflect() protoreflect.Message {
	mi := &file_fence_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeForPairingDevice.ProtoReflect.Descriptor instead.
func (*CodeForPairingDevice) Descriptor() ([]byte, []int) {
	return file_fence_service_proto_rawDescGZIP(), []int{22}
}

func (x *CodeForPairingDevice) GetFirmId() string {
	if x != nil {
		return x.FirmId
	}
	return ""
}

func (x *CodeForPairingDevice) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *CodeForPairingDevice) GetBoutiqueId() string {
	if x != nil {
		return x.BoutiqueId
	}
	return ""
}

func (x *CodeForPairingDevice) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CodeForPairingDevice) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CodeForPairingDevice) GetTimestampUTC() *timestamppb.Timestamp {
	if x != nil {
		return x.TimestampUTC
	}
	return nil
}

type ApproveDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *device.Device         `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveDeviceRequest) Reset() {
	*x = ApproveDeviceRequest{}
	mi := &file_fence_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveDeviceRequest) ProtoMessage() {}

func (x *ApproveDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fence_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveDeviceRequest.ProtoReflect.Descriptor instead.
func (*ApproveDeviceRequest) Descriptor() ([]byte, []int) {
	return file_fence_service_proto_rawDescGZIP(), []int{23}
}

func (x *ApproveDeviceRequest) GetDevice() *device.Device {
	if x != nil {
		return x.Device
	}
	return nil
}

type PasswordResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mail          string                 `protobuf:"bytes,1,opt,name=mail,proto3" json:"mail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordResetRequest) Reset() {
	*x = PasswordResetRequest{}
	mi := &file_fence_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordResetRequest) ProtoMessage() {}

func (x *PasswordResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fence_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordResetRequest.ProtoReflect.Descriptor instead.
func (*PasswordResetRequest) Descriptor() ([]byte, []int) {
	return file_fence_service_proto_rawDescGZIP(), []int{24}
}

func (x *PasswordResetRequest) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

type PasswordResetConfirmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mail          string                 `protobuf:"bytes,1,opt,name=mail,proto3" json:"mail,omitempty"`
	ResetToken    string                 `protobuf:"bytes,2,opt,name=resetToken,proto3" json:"resetToken,omitempty"`
	NewPassword   string                 `protobuf:"bytes,3,opt,name=newPassword,proto3" json:"newPassword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordResetConfirmRequest) Reset() {
	*x = PasswordResetConfirmRequest{}
	mi := &file_fence_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordResetConfirmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordResetConfirmRequest) ProtoMessage() {}

func (x *PasswordResetConfirmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fence_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordResetConfirmRequest.ProtoReflect.Descriptor instead.
func (*PasswordResetConfirmRequest) Descriptor() ([]byte, []int) {
	return file_fence_service_proto_rawDescGZIP(), []int{25}
}

func (x *PasswordResetConfirmRequest) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

func (x *PasswordResetConfirmRequest) GetResetToken() string {
	if x != nil {
		return x.ResetToken
	}
	return ""
}

func (x *PasswordResetConfirmRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type MarkEmailVerifiedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mail          string                 `protobuf:"bytes,1,opt,name=mail,proto3" json:"mail,omitempty"`     // Required - email is unique per user
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"` // Optional - if provided, used directly for better performance
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkEmailVerifiedRequest) Reset() {
	*x = MarkEmailVerifiedRequest{}
	mi := &file_fence_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkEmailVerifiedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkEmailVerifiedRequest) ProtoMessage() {}

func (x *MarkEmailVerifiedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fence_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkEmailVerifiedRequest.ProtoReflect.Descriptor instead.
func (*MarkEmailVerifiedRequest) Descriptor() ([]byte, []int) {
	return file_fence_service_proto_rawDescGZIP(), []int{26}
}

func (x *MarkEmailVerifiedRequest) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

func (x *MarkEmailVerifiedRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateSubscriberIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mail          string                 `protobuf:"bytes,1,opt,name=mail,proto3" json:"mail,omitempty"`                 // Required - email is unique per user
	SubscriberId  string                 `protobuf:"bytes,2,opt,name=subscriberId,proto3" json:"subscriberId,omitempty"` // Required - subscriber ID to link
	UserId        string                 `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`             // Optional - if provided, used directly for better performance
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSubscriberIdRequest) Reset() {
	*x = UpdateSubscriberIdRequest{}
	mi := &file_fence_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSubscriberIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSubscriberIdRequest) ProtoMessage() {}

func (x *UpdateSubscriberIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fence_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSubscriberIdRequest.ProtoReflect.Descriptor instead.
func (*UpdateSubscriberIdRequest) Descriptor() ([]byte, []int) {
	return file_fence_service_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateSubscriberIdRequest) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

func (x *UpdateSubscriberIdRequest) GetSubscriberId() string {
	if x != nil {
		return x.SubscriberId
	}
	return ""
}

func (x *UpdateSubscriberIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// / Health check response with service versions
type HealthCheckWeebiResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Status          string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp       string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Versions        *ServiceVersions       `protobuf:"bytes,3,opt,name=versions,proto3" json:"versions,omitempty"`
	DatabaseHealthy bool                   `protobuf:"varint,4,opt,name=databaseHealthy,proto3" json:"databaseHealthy,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HealthCheckWeebiResponse) Reset() {
	*x = HealthCheckWeebiResponse{}
	mi := &file_fence_service_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckWeebiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckWeebiResponse) ProtoMessage() {}

func (x *HealthCheckWeebiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fence_service_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckWeebiResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckWeebiResponse) Descriptor() ([]byte, []int) {
	return file_fence_service_proto_rawDescGZIP(), []int{28}
}

func (x *HealthCheckWeebiResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckWeebiResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *HealthCheckWeebiResponse) GetVersions() *ServiceVersions {
	if x != nil {
		return x.Versions
	}
	return nil
}

func (x *HealthCheckWeebiResponse) GetDatabaseHealthy() bool {
	if x != nil {
		return x.DatabaseHealthy
	}
	return false
}

type ServiceVersions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        string                 `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	ProtosWeebi   string                 `protobuf:"bytes,2,opt,name=protos_weebi,proto3" json:"protos_weebi,omitempty"`
	FenceService  string                 `protobuf:"bytes,3,opt,name=fence_service,proto3" json:"fence_service,omitempty"`
	ModelsWeebi   string                 `protobuf:"bytes,4,opt,name=models_weebi,proto3" json:"models_weebi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceVersions) Reset() {
	*x = ServiceVersions{}
	mi := &file_fence_service_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceVersions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceVersions) ProtoMessage() {}

func (x *ServiceVersions) ProtoReflect() protoreflect.Message {
	mi := &file_fence_service_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceVersions.ProtoReflect.Descriptor instead.
func (*ServiceVersions) Descriptor() ([]byte, []int) {
	return file_fence_service_proto_rawDescGZIP(), []int{29}
}

func (x *ServiceVersions) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *ServiceVersions) GetProtosWeebi() string {
	if x != nil {
		return x.ProtosWeebi
	}
	return ""
}

func (x *ServiceVersions) GetFenceService() string {
	if x != nil {
		return x.FenceService
	}
	return ""
}

func (x *ServiceVersions) GetModelsWeebi() string {
	if x != nil {
		return x.ModelsWeebi
	}
	return ""
}

var File_fence_service_proto protoreflect.FileDescriptor

const file_fence_service_proto_rawDesc = "" +
	"\n" +
	"\x13fence_service.proto\x12\x13weebi.fence.service\x1a\x18common/chained_ids.proto\x1a\x12common/empty.proto\x1a\x15common/g_common.proto\x1a\x18common/g_timestamp.proto\x1a\n" +
	"user.proto\x1a\x16user_permissions.proto\x1a\n" +
	"firm.proto\x1a\x0fbtq_chain.proto\x1a\x0eboutique.proto\x1a\fdevice.proto\"<\n" +
	"\fChainRequest\x12\x18\n" +
	"\achainId\x18\x01 \x01(\tR\achainId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x9d\x01\n" +
	"\x0fBoutiqueRequest\x12\x18\n" +
	"\achainId\x18\x01 \x01(\tR\achainId\x126\n" +
	"\bboutique\x18\x02 \x01(\v2\x1a.weebi.boutique.BoutiquePbR\bboutique\x12\x12\n" +
	"\x04logo\x18\x03 \x01(\fR\x04logo\x12$\n" +
	"\rlogoExtension\x18\x04 \x01(\tR\rlogoExtension\"\x84\x01\n" +
	"\x10BoutiqueResponse\x126\n" +
	"\bboutique\x18\x01 \x01(\v2\x1a.weebi.boutique.BoutiquePbR\bboutique\x12\x12\n" +
	"\x04logo\x18\x02 \x01(\fR\x04logo\x12$\n" +
	"\rlogoExtension\x18\x03 \x01(\tR\rlogoExtension\"\xd2\x01\n" +
	"\x14CreateDeviceResponse\x12L\n" +
	"\x0estatusResponse\x18\x01 \x01(\v2$.google.retail.common.StatusResponseR\x0estatusResponse\x12\x16\n" +
	"\x06firmId\x18\x02 \x01(\tR\x06firmId\x12\x18\n" +
	"\achainId\x18\x03 \x01(\tR\achainId\x12\x1e\n" +
	"\n" +
	"boutiqueId\x18\x04 \x01(\tR\n" +
	"boutiqueId\x12\x1a\n" +
	"\bdeviceId\x18\x05 \x01(\tR\bdeviceId\"\x8f\x01\n" +
	"\x13ReadOneUserResponse\x12L\n" +
	"\x0estatusResponse\x18\x01 \x01(\v2$.google.retail.common.StatusResponseR\x0estatusResponse\x12*\n" +
	"\x04user\x18\x02 \x01(\v2\x16.weebi.user.UserPublicR\x04user\";\n" +
	"\vUsersPublic\x12,\n" +
	"\x05users\x18\x01 \x03(\v2\x16.weebi.user.UserPublicR\x05users\"C\n" +
	"\x15ReadAllChainsResponse\x12*\n" +
	"\x06chains\x18\x01 \x03(\v2\x12.weebi.chain.ChainR\x06chains\"T\n" +
	"\x18ReadAllBoutiquesResponse\x128\n" +
	"\tboutiques\x18\x01 \x03(\v2\x1a.weebi.boutique.BoutiquePbR\tboutiques\".\n" +
	"\x12ReadDevicesRequest\x12\x18\n" +
	"\achainId\x18\x01 \x01(\tR\achainId\"8\n" +
	"\x18IsADeviceInChainResponse\x12\x1c\n" +
	"\tisADevice\x18\x01 \x01(\bR\tisADevice\"P\n" +
	"\x14ReadDeviceBtqRequest\x12\x18\n" +
	"\achainId\x18\x01 \x01(\tR\achainId\x12\x1e\n" +
	"\n" +
	"boutiqueId\x18\x02 \x01(\tR\n" +
	"boutiqueId\"]\n" +
	"\x13DeleteDeviceRequest\x12\x18\n" +
	"\achainId\x18\x01 \x01(\tR\achainId\x12,\n" +
	"\x06device\x18\x02 \x01(\v2\x14.weebi.device.DeviceR\x06device\"[\n" +
	"\x17MailAndEncyptedPassword\x12\x12\n" +
	"\x04mail\x18\x01 \x01(\tR\x04mail\x12,\n" +
	"\x11passwordEncrypted\x18\x02 \x01(\tR\x11passwordEncrypted\" \n" +
	"\x06UserId\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"\x8d\x01\n" +
	"\x06Access\x12<\n" +
	"\bchainIds\x18\x01 \x01(\v2 .weebi.user.permissions.ChainIdsR\bchainIds\x12E\n" +
	"\vboutiqueIds\x18\x02 \x01(\v2#.weebi.user.permissions.BoutiqueIdsR\vboutiqueIds\"Y\n" +
	"\vCredentials\x12\x12\n" +
	"\x04mail\x18\x01 \x01(\tR\x04mail\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1a\n" +
	"\bisWebApp\x18\x03 \x01(\bR\bisWebApp\"\x9d\x01\n" +
	"\x11DeviceCredentials\x12\x16\n" +
	"\x06firmId\x18\x01 \x01(\tR\x06firmId\x12\x18\n" +
	"\achainId\x18\x02 \x01(\tR\achainId\x12\x1e\n" +
	"\n" +
	"boutiqueId\x18\x03 \x01(\tR\n" +
	"boutiqueId\x12\x1a\n" +
	"\bdeviceId\x18\x04 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\"2\n" +
	"\fRefreshToken\x12\"\n" +
	"\frefreshToken\x18\x01 \x01(\tR\frefreshToken\"\x9c\x01\n" +
	"\x06Tokens\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12\"\n" +
	"\frefreshToken\x18\x02 \x01(\tR\frefreshToken\x12.\n" +
	"\x12mustChangePassword\x18\x03 \x01(\bR\x12mustChangePassword\x12\x1c\n" +
	"\tsessionId\x18\x04 \x01(\tR\tsessionId\"e\n" +
	"\x1bUpdateDevicePasswordRequest\x12\x18\n" +
	"\achainId\x18\x01 \x01(\tR\achainId\x12,\n" +
	"\x06device\x18\x02 \x01(\v2\x14.weebi.device.DeviceR\x06device\"\x93\x01\n" +
	"\x15PasswordUpdateRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06firmId\x18\x02 \x01(\tR\x06firmId\x12(\n" +
	"\x0fpasswordCurrent\x18\x03 \x01(\tR\x0fpasswordCurrent\x12 \n" +
	"\vpasswordNew\x18\x04 \x01(\tR\vpasswordNew\"j\n" +
	"\x14PendingDeviceRequest\x12>\n" +
	"\fhardwareInfo\x18\x01 \x01(\v2\x1a.weebi.device.HardwareInfoR\fhardwareInfo\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\"\xd4\x01\n" +
	"\x14CodeForPairingDevice\x12\x16\n" +
	"\x06firmId\x18\x01 \x01(\tR\x06firmId\x12\x18\n" +
	"\achainId\x18\x02 \x01(\tR\achainId\x12\x1e\n" +
	"\n" +
	"boutiqueId\x18\x03 \x01(\tR\n" +
	"boutiqueId\x12\x16\n" +
	"\x06userId\x18\x04 \x01(\tR\x06userId\x12\x12\n" +
	"\x04code\x18\x05 \x01(\x05R\x04code\x12>\n" +
	"\ftimestampUTC\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ftimestampUTC\"D\n" +
	"\x14ApproveDeviceRequest\x12,\n" +
	"\x06device\x18\x01 \x01(\v2\x14.weebi.device.DeviceR\x06device\"*\n" +
	"\x14PasswordResetRequest\x12\x12\n" +
	"\x04mail\x18\x01 \x01(\tR\x04mail\"s\n" +
	"\x1bPasswordResetConfirmRequest\x12\x12\n" +
	"\x04mail\x18\x01 \x01(\tR\x04mail\x12\x1e\n" +
	"\n" +
	"resetToken\x18\x02 \x01(\tR\n" +
	"resetToken\x12 \n" +
	"\vnewPassword\x18\x03 \x01(\tR\vnewPassword\"F\n" +
	"\x18MarkEmailVerifiedRequest\x12\x12\n" +
	"\x04mail\x18\x01 \x01(\tR\x04mail\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\"k\n" +
	"\x19UpdateSubscriberIdRequest\x12\x12\n" +
	"\x04mail\x18\x01 \x01(\tR\x04mail\x12\"\n" +
	"\fsubscriberId\x18\x02 \x01(\tR\fsubscriberId\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\tR\x06userId\"\xbc\x01\n" +
	"\x18HealthCheckWeebiResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12@\n" +
	"\bversions\x18\x03 \x01(\v2$.weebi.fence.service.ServiceVersionsR\bversions\x12(\n" +
	"\x0fdatabaseHealthy\x18\x04 \x01(\bR\x0fdatabaseHealthy\"\x97\x01\n" +
	"\x0fServiceVersions\x12\x16\n" +
	"\x06server\x18\x01 \x01(\tR\x06server\x12\"\n" +
	"\fprotos_weebi\x18\x02 \x01(\tR\fprotos_weebi\x12$\n" +
	"\rfence_service\x18\x03 \x01(\tR\rfence_service\x12\"\n" +
	"\fmodels_weebi\x18\x04 \x01(\tR\fmodels_weebi2\xc7\x18\n" +
	"\fFenceService\x12W\n" +
	"\vhealthCheck\x12\x19.weebi.common.empty.Empty\x1a-.weebi.fence.service.HealthCheckWeebiResponse\x12?\n" +
	"\x06signUp\x12\x19.weebi.user.SignUpRequest\x1a\x1a.weebi.user.SignUpResponse\x12\\\n" +
	"\x1bauthenticateWithCredentials\x12 .weebi.fence.service.Credentials\x1a\x1b.weebi.fence.service.Tokens\x12^\n" +
	"\x1cauthenticateWithRefreshToken\x12!.weebi.fence.service.RefreshToken\x1a\x1b.weebi.fence.service.Tokens\x12>\n" +
	"\x06logout\x12\x19.weebi.common.empty.Empty\x1a\x19.weebi.common.empty.Empty\x12g\n" +
	"\x14requestPasswordReset\x12).weebi.fence.service.PasswordResetRequest\x1a$.google.retail.common.StatusResponse\x12n\n" +
	"\x14confirmPasswordReset\x120.weebi.fence.service.PasswordResetConfirmRequest\x1a$.google.retail.common.StatusResponse\x12K\n" +
	"\n" +
	"createFirm\x12\x1d.weebi.firm.CreateFirmRequest\x1a\x1e.weebi.firm.CreateFirmResponse\x12:\n" +
	"\vreadOneFirm\x12\x19.weebi.common.empty.Empty\x1a\x10.weebi.firm.Firm\x12T\n" +
	"\x11createPendingUser\x12\x1e.weebi.user.PendingUserRequest\x1a\x1f.weebi.user.PendingUserResponse\x12T\n" +
	"\vreadOneUser\x12\x1b.weebi.fence.service.UserId\x1a(.weebi.fence.service.ReadOneUserResponse\x12K\n" +
	"\freadAllUsers\x12\x19.weebi.common.empty.Empty\x1a .weebi.fence.service.UsersPublic\x12M\n" +
	"\rupdateOneUser\x12\x16.weebi.user.UserPublic\x1a$.google.retail.common.StatusResponse\x12f\n" +
	"\x12updateUserPassword\x12*.weebi.fence.service.PasswordUpdateRequest\x1a$.google.retail.common.StatusResponse\x12R\n" +
	"\rdeleteOneUser\x12\x1b.weebi.fence.service.UserId\x1a$.google.retail.common.StatusResponse\x12h\n" +
	"\x11markEmailVerified\x12-.weebi.fence.service.MarkEmailVerifiedRequest\x1a$.google.retail.common.StatusResponse\x12j\n" +
	"\x12updateSubscriberId\x12..weebi.fence.service.UpdateSubscriberIdRequest\x1a$.google.retail.common.StatusResponse\x12J\n" +
	"\x0ecreateOneChain\x12\x12.weebi.chain.Chain\x1a$.google.retail.common.StatusResponse\x12V\n" +
	"\rreadAllChains\x12\x19.weebi.common.empty.Empty\x1a*.weebi.fence.service.ReadAllChainsResponse\x12Y\n" +
	"\x0eupdateOneChain\x12!.weebi.fence.service.ChainRequest\x1a$.google.retail.common.StatusResponse\x12Y\n" +
	"\x0edeleteOneChain\x12!.weebi.fence.service.ChainRequest\x1a$.google.retail.common.StatusResponse\x12_\n" +
	"\x11createOneBoutique\x12$.weebi.fence.service.BoutiqueRequest\x1a$.google.retail.common.StatusResponse\x12^\n" +
	"\x0freadOneBoutique\x12$.weebi.fence.service.BoutiqueRequest\x1a%.weebi.fence.service.BoutiqueResponse\x12_\n" +
	"\x11updateOneBoutique\x12$.weebi.fence.service.BoutiqueRequest\x1a$.google.retail.common.StatusResponse\x12_\n" +
	"\x11deleteOneBoutique\x12$.weebi.fence.service.BoutiqueRequest\x1a$.google.retail.common.StatusResponse\x12`\n" +
	"\x12restoreOneBoutique\x12$.weebi.fence.service.BoutiqueRequest\x1a$.google.retail.common.StatusResponse\x12\\\n" +
	"\x10readAllBoutiques\x12\x19.weebi.common.empty.Empty\x1a-.weebi.fence.service.ReadAllBoutiquesResponse\x12j\n" +
	"\x10isADeviceInChain\x12'.weebi.fence.service.ReadDevicesRequest\x1a-.weebi.fence.service.IsADeviceInChainResponse\x12M\n" +
	"\vreadDevices\x12'.weebi.fence.service.ReadDevicesRequest\x1a\x15.weebi.device.Devices\x12y\n" +
	"\x1cgenerateCodeForPairingDevice\x12..weebi.common.chained_ids.ChainIdAndboutiqueId\x1a).weebi.fence.service.CodeForPairingDevice\x12W\n" +
	"\x14readOnePendingDevice\x12).weebi.fence.service.ReadDeviceBtqRequest\x1a\x14.weebi.device.Device\x12d\n" +
	"\fcreateDevice\x12).weebi.fence.service.PendingDeviceRequest\x1a).weebi.fence.service.CreateDeviceResponse\x12n\n" +
	"\x14updateDevicePassword\x120.weebi.fence.service.UpdateDevicePasswordRequest\x1a$.google.retail.common.StatusResponse\x12a\n" +
	"\x0fdeleteOneDevice\x12(.weebi.fence.service.DeleteDeviceRequest\x1a$.google.retail.common.StatusResponseb\x06proto3"

var (
	file_fence_service_proto_rawDescOnce sync.Once
	file_fence_service_proto_rawDescData []byte
)

func file_fence_service_proto_rawDescGZIP() []byte {
	file_fence_service_proto_rawDescOnce.Do(func() {
		file_fence_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fence_service_proto_rawDesc), len(file_fence_service_proto_rawDesc)))
	})
	return file_fence_service_proto_rawDescData
}

var file_fence_service_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_fence_service_proto_goTypes = []any{
	(*ChainRequest)(nil),                     // 0: weebi.fence.service.ChainRequest
	(*BoutiqueRequest)(nil),                  // 1: weebi.fence.service.BoutiqueRequest
	(*BoutiqueResponse)(nil),                 // 2: weebi.fence.service.BoutiqueResponse
	(*CreateDeviceResponse)(nil),             // 3: weebi.fence.service.CreateDeviceResponse
	(*ReadOneUserResponse)(nil),              // 4: weebi.fence.service.ReadOneUserResponse
	(*UsersPublic)(nil),                      // 5: weebi.fence.service.UsersPublic
	(*ReadAllChainsResponse)(nil),            // 6: weebi.fence.service.ReadAllChainsResponse
	(*ReadAllBoutiquesResponse)(nil),         // 7: weebi.fence.service.ReadAllBoutiquesResponse
	(*ReadDevicesRequest)(nil),               // 8: weebi.fence.service.ReadDevicesRequest
	(*IsADeviceInChainResponse)(nil),         // 9: weebi.fence.service.IsADeviceInChainResponse
	(*ReadDeviceBtqRequest)(nil),             // 10: weebi.fence.service.ReadDeviceBtqRequest
	(*DeleteDeviceRequest)(nil),              // 11: weebi.fence.service.DeleteDeviceRequest
	(*MailAndEncyptedPassword)(nil),          // 12: weebi.fence.service.MailAndEncyptedPassword
	(*UserId)(nil),                           // 13: weebi.fence.service.UserId
	(*Access)(nil),                           // 14: weebi.fence.service.Access
	(*Credentials)(nil),                      // 15: weebi.fence.service.Credentials
	(*DeviceCredentials)(nil),                // 16: weebi.fence.service.DeviceCredentials
	(*RefreshToken)(nil),                     // 17: weebi.fence.service.RefreshToken
	(*Tokens)(nil),                           // 18: weebi.fence.service.Tokens
	(*UpdateDevicePasswordRequest)(nil),      // 19: weebi.fence.service.UpdateDevicePasswordRequest
	(*PasswordUpdateRequest)(nil),            // 20: weebi.fence.service.PasswordUpdateRequest
	(*PendingDeviceRequest)(nil),             // 21: weebi.fence.service.PendingDeviceRequest
	(*CodeForPairingDevice)(nil),             // 22: weebi.fence.service.CodeForPairingDevice
	(*ApproveDeviceRequest)(nil),             // 23: weebi.fence.service.ApproveDeviceRequest
	(*PasswordResetRequest)(nil),             // 24: weebi.fence.service.PasswordResetRequest
	(*PasswordResetConfirmRequest)(nil),      // 25: weebi.fence.service.PasswordResetConfirmRequest
	(*MarkEmailVerifiedRequest)(nil),         // 26: weebi.fence.service.MarkEmailVerifiedRequest
	(*UpdateSubscriberIdRequest)(nil),        // 27: weebi.fence.service.UpdateSubscriberIdRequest
	(*HealthCheckWeebiResponse)(nil),         // 28: weebi.fence.service.HealthCheckWeebiResponse
	(*ServiceVersions)(nil),                  // 29: weebi.fence.service.ServiceVersions
	(*boutique.BoutiquePb)(nil),              // 30: weebi.boutique.BoutiquePb
	(*g_common.StatusResponse)(nil),          // 31: google.retail.common.StatusResponse
	(*user.UserPublic)(nil),                  // 32: weebi.user.UserPublic
	(*btq_chain.Chain)(nil),                  // 33: weebi.chain.Chain
	(*device.Device)(nil),                    // 34: weebi.device.Device
	(*user_permissions.ChainIds)(nil),        // 35: weebi.user.permissions.ChainIds
	(*user_permissions.BoutiqueIds)(nil),     // 36: weebi.user.permissions.BoutiqueIds
	(*device.HardwareInfo)(nil),              // 37: weebi.device.HardwareInfo
	(*timestamppb.Timestamp)(nil),            // 38: google.protobuf.Timestamp
	(*empty.Empty)(nil),                      // 39: weebi.common.empty.Empty
	(*user.SignUpRequest)(nil),               // 40: weebi.user.SignUpRequest
	(*firm.CreateFirmRequest)(nil),           // 41: weebi.firm.CreateFirmRequest
	(*user.PendingUserRequest)(nil),          // 42: weebi.user.PendingUserRequest
	(*chained_ids.ChainIdAndboutiqueId)(nil), // 43: weebi.common.chained_ids.ChainIdAndboutiqueId
	(*user.SignUpResponse)(nil),              // 44: weebi.user.SignUpResponse
	(*firm.CreateFirmResponse)(nil),          // 45: weebi.firm.CreateFirmResponse
	(*firm.Firm)(nil),                        // 46: weebi.firm.Firm
	(*user.PendingUserResponse)(nil),         // 47: weebi.user.PendingUserResponse
	(*device.Devices)(nil),                   // 48: weebi.device.Devices
}
var file_fence_service_proto_depIdxs = []int32{
	30, // 0: weebi.fence.service.BoutiqueRequest.boutique:type_name -> weebi.boutique.BoutiquePb
	30, // 1: weebi.fence.service.BoutiqueResponse.boutique:type_name -> weebi.boutique.BoutiquePb
	31, // 2: weebi.fence.service.CreateDeviceResponse.statusResponse:type_name -> google.retail.common.StatusResponse
	31, // 3: weebi.fence.service.ReadOneUserResponse.statusResponse:type_name -> google.retail.common.StatusResponse
	32, // 4: weebi.fence.service.ReadOneUserResponse.user:type_name -> weebi.user.UserPublic
	32, // 5: weebi.fence.service.UsersPublic.users:type_name -> weebi.user.UserPublic
	33, // 6: weebi.fence.service.ReadAllChainsResponse.chains:type_name -> weebi.chain.Chain
	30, // 7: weebi.fence.service.ReadAllBoutiquesResponse.boutiques:type_name -> weebi.boutique.BoutiquePb
	34, // 8: weebi.fence.service.DeleteDeviceRequest.device:type_name -> weebi.device.Device
	35, // 9: weebi.fence.service.Access.chainIds:type_name -> weebi.user.permissions.ChainIds
	36, // 10: weebi.fence.service.Access.boutiqueIds:type_name -> weebi.user.permissions.BoutiqueIds
	34, // 11: weebi.fence.service.UpdateDevicePasswordRequest.device:type_name -> weebi.device.Device
	37, // 12: weebi.fence.service.PendingDeviceRequest.hardwareInfo:type_name -> weebi.device.HardwareInfo
	38, // 13: weebi.fence.service.CodeForPairingDevice.timestampUTC:type_name -> google.protobuf.Timestamp
	34, // 14: weebi.fence.service.ApproveDeviceRequest.device:type_name -> weebi.device.Device
	29, // 15: weebi.fence.service.HealthCheckWeebiResponse.versions:type_name -> weebi.fence.service.ServiceVersions
	39, // 16: weebi.fence.service.FenceService.healthCheck:input_type -> weebi.common.empty.Empty
	40, // 17: weebi.fence.service.FenceService.signUp:input_type -> weebi.user.SignUpRequest
	15, // 18: weebi.fence.service.FenceService.authenticateWithCredentials:input_type -> weebi.fence.service.Credentials
	17, // 19: weebi.fence.service.FenceService.authenticateWithRefreshToken:input_type -> weebi.fence.service.RefreshToken
	39, // 20: weebi.fence.service.FenceService.logout:input_type -> weebi.common.empty.Empty
	24, // 21: weebi.fence.service.FenceService.requestPasswordReset:input_type -> weebi.fence.service.PasswordResetRequest
	25, // 22: weebi.fence.service.FenceService.confirmPasswordReset:input_type -> weebi.fence.service.PasswordResetConfirmRequest
	41, // 23: weebi.fence.service.FenceService.createFirm:input_type -> weebi.firm.CreateFirmRequest
	39, // 24: weebi.fence.service.FenceService.readOneFirm:input_type -> weebi.common.empty.Empty
	42, // 25: weebi.fence.service.FenceService.createPendingUser:input_type -> weebi.user.PendingUserRequest
	13, // 26: weebi.fence.service.FenceService.readOneUser:input_type -> weebi.fence.service.UserId
	39, // 27: weebi.fence.service.FenceService.readAllUsers:input_type -> weebi.common.empty.Empty
	32, // 28: weebi.fence.service.FenceService.updateOneUser:input_type -> weebi.user.UserPublic
	20, // 29: weebi.fence.service.FenceService.updateUserPassword:input_type -> weebi.fence.service.PasswordUpdateRequest
	13, // 30: weebi.fence.service.FenceService.deleteOneUser:input_type -> weebi.fence.service.UserId
	26, // 31: weebi.fence.service.FenceService.markEmailVerified:input_type -> weebi.fence.service.MarkEmailVerifiedRequest
	27, // 32: weebi.fence.service.FenceService.updateSubscriberId:input_type -> weebi.fence.service.UpdateSubscriberIdRequest
	33, // 33: weebi.fence.service.FenceService.createOneChain:input_type -> weebi.chain.Chain
	39, // 34: weebi.fence.service.FenceService.readAllChains:input_type -> weebi.common.empty.Empty
	0,  // 35: weebi.fence.service.FenceService.updateOneChain:input_type -> weebi.fence.service.ChainRequest
	0,  // 36: weebi.fence.service.FenceService.deleteOneChain:input_type -> weebi.fence.service.ChainRequest
	1,  // 37: weebi.fence.service.FenceService.createOneBoutique:input_type -> weebi.fence.service.BoutiqueRequest
	1,  // 38: weebi.fence.service.FenceService.readOneBoutique:input_type -> weebi.fence.service.BoutiqueRequest
	1,  // 39: weebi.fence.service.FenceService.updateOneBoutique:input_type -> weebi.fence.service.BoutiqueRequest
	1,  // 40: weebi.fence.service.FenceService.deleteOneBoutique:input_type -> weebi.fence.service.BoutiqueRequest
	1,  // 41: weebi.fence.service.FenceService.restoreOneBoutique:input_type -> weebi.fence.service.BoutiqueRequest
	39, // 42: weebi.fence.service.FenceService.readAllBoutiques:input_type -> weebi.common.empty.Empty
	8,  // 43: weebi.fence.service.FenceService.isADeviceInChain:input_type -> weebi.fence.service.ReadDevicesRequest
	8,  // 44: weebi.fence.service.FenceService.readDevices:input_type -> weebi.fence.service.ReadDevicesRequest
	43, // 45: weebi.fence.service.FenceService.generateCodeForPairingDevice:input_type -> weebi.common.chained_ids.ChainIdAndboutiqueId
	10, // 46: weebi.fence.service.FenceService.readOnePendingDevice:input_type -> weebi.fence.service.ReadDeviceBtqRequest
	21, // 47: weebi.fence.service.FenceService.createDevice:input_type -> weebi.fence.service.PendingDeviceRequest
	19, // 48: weebi.fence.service.FenceService.updateDevicePassword:input_type -> weebi.fence.service.UpdateDevicePasswordRequest
	11, // 49: weebi.fence.service.FenceService.deleteOneDevice:input_type -> weebi.fence.service.DeleteDeviceRequest
	28, // 50: weebi.fence.service.FenceService.healthCheck:output_type -> weebi.fence.service.HealthCheckWeebiResponse
	44, // 51: weebi.fence.service.FenceService.signUp:output_type -> weebi.user.SignUpResponse
	18, // 52: weebi.fence.service.FenceService.authenticateWithCredentials:output_type -> weebi.fence.service.Tokens
	18, // 53: weebi.fence.service.FenceService.authenticateWithRefreshToken:output_type -> weebi.fence.service.Tokens
	39, // 54: weebi.fence.service.FenceService.logout:output_type -> weebi.common.empty.Empty
	31, // 55: weebi.fence.service.FenceService.requestPasswordReset:output_type -> google.retail.common.StatusResponse
	31, // 56: weebi.fence.service.FenceService.confirmPasswordReset:output_type -> google.retail.common.StatusResponse
	45, // 57: weebi.fence.service.FenceService.createFirm:output_type -> weebi.firm.CreateFirmResponse
	46, // 58: weebi.fence.service.FenceService.readOneFirm:output_type -> weebi.firm.Firm
	47, // 59: weebi.fence.service.FenceService.createPendingUser:output_type -> weebi.user.PendingUserResponse
	4,  // 60: weebi.fence.service.FenceService.readOneUser:output_type -> weebi.fence.service.ReadOneUserResponse
	5,  // 61: weebi.fence.service.FenceService.readAllUsers:output_type -> weebi.fence.service.UsersPublic
	31, // 62: weebi.fence.service.FenceService.updateOneUser:output_type -> google.retail.common.StatusResponse
	31, // 63: weebi.fence.service.FenceService.updateUserPassword:output_type -> google.retail.common.StatusResponse
	31, // 64: weebi.fence.service.FenceService.deleteOneUser:output_type -> google.retail.common.StatusResponse
	31, // 65: weebi.fence.service.FenceService.markEmailVerified:output_type -> google.retail.common.StatusResponse
	31, // 66: weebi.fence.service.FenceService.updateSubscriberId:output_type -> google.retail.common.StatusResponse
	31, // 67: weebi.fence.service.FenceService.createOneChain:output_type -> google.retail.common.StatusResponse
	6,  // 68: weebi.fence.service.FenceService.readAllChains:output_type -> weebi.fence.service.ReadAllChainsResponse
	31, // 69: weebi.fence.service.FenceService.updateOneChain:output_type -> google.retail.common.StatusResponse
	31, // 70: weebi.fence.service.FenceService.deleteOneChain:output_type -> google.retail.common.StatusResponse
	31, // 71: weebi.fence.service.FenceService.createOneBoutique:output_type -> google.retail.common.StatusResponse
	2,  // 72: weebi.fence.service.FenceService.readOneBoutique:output_type -> weebi.fence.service.BoutiqueResponse
	31, // 73: weebi.fence.service.FenceService.updateOneBoutique:output_type -> google.retail.common.StatusResponse
	31, // 74: weebi.fence.service.FenceService.deleteOneBoutique:output_type -> google.retail.common.StatusResponse
	31, // 75: weebi.fence.service.FenceService.restoreOneBoutique:output_type -> google.retail.common.StatusResponse
	7,  // 76: weebi.fence.service.FenceService.readAllBoutiques:output_type -> weebi.fence.service.ReadAllBoutiquesResponse
	9,  // 77: weebi.fence.service.FenceService.isADeviceInChain:output_type -> weebi.fence.service.IsADeviceInChainResponse
	48, // 78: weebi.fence.service.FenceService.readDevices:output_type -> weebi.device.Devices
	22, // 79: weebi.fence.service.FenceService.generateCodeForPairingDevice:output_type -> weebi.fence.service.CodeForPairingDevice
	34, // 80: weebi.fence.service.FenceService.readOnePendingDevice:output_type -> weebi.device.Device
	3,  // 81: weebi.fence.service.FenceService.createDevice:output_type -> weebi.fence.service.CreateDeviceResponse
	31, // 82: weebi.fence.service.FenceService.updateDevicePassword:output_type -> google.retail.common.StatusResponse
	31, // 83: weebi.fence.service.FenceService.deleteOneDevice:output_type -> google.retail.common.StatusResponse
	50, // [50:84] is the sub-list for method output_type
	16, // [16:50] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_fence_service_proto_init() }
func file_fence_service_proto_init() {
	if File_fence_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fence_service_proto_rawDesc), len(file_fence_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fence_service_proto_goTypes,
		DependencyIndexes: file_fence_service_proto_depIdxs,
		MessageInfos:      file_fence_service_proto_msgTypes,
	}.Build()
	File_fence_service_proto = out.File
	file_fence_service_proto_goTypes = nil
	file_fence_service_proto_depIdxs = nil
}
