// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: billing_service.proto

package service

import (
	empty "github.com/weebi-com/protos/common/empty"
	g_common "github.com/weebi-com/protos/common/g_common"
	g_timestamp "github.com/weebi-com/protos/common/g_timestamp"
	license "github.com/weebi-com/protos/license"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateLicenseRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	License *license.License       `protobuf:"bytes,1,opt,name=license,proto3" json:"license,omitempty"`
	// / Referral code used by the buyer (e.g. from shopkeeper who referred them).
	ReferralCode string `protobuf:"bytes,2,opt,name=referralCode,proto3" json:"referralCode,omitempty"`
	// / Amount of referral credit (cents) to apply. Deducted from buyer's firm balance.
	CreditAppliedCents int32 `protobuf:"varint,3,opt,name=creditAppliedCents,proto3" json:"creditAppliedCents,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateLicenseRequest) Reset() {
	*x = CreateLicenseRequest{}
	mi := &file_billing_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLicenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLicenseRequest) ProtoMessage() {}

func (x *CreateLicenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLicenseRequest.ProtoReflect.Descriptor instead.
func (*CreateLicenseRequest) Descriptor() ([]byte, []int) {
	return file_billing_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLicenseRequest) GetLicense() *license.License {
	if x != nil {
		return x.License
	}
	return nil
}

func (x *CreateLicenseRequest) GetReferralCode() string {
	if x != nil {
		return x.ReferralCode
	}
	return ""
}

func (x *CreateLicenseRequest) GetCreditAppliedCents() int32 {
	if x != nil {
		return x.CreditAppliedCents
	}
	return 0
}

type CreateLicenseResponse struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	StatusResponse *g_common.StatusResponse `protobuf:"bytes,1,opt,name=statusResponse,proto3" json:"statusResponse,omitempty"`
	License        *license.License         `protobuf:"bytes,2,opt,name=license,proto3" json:"license,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateLicenseResponse) Reset() {
	*x = CreateLicenseResponse{}
	mi := &file_billing_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLicenseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLicenseResponse) ProtoMessage() {}

func (x *CreateLicenseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLicenseResponse.ProtoReflect.Descriptor instead.
func (*CreateLicenseResponse) Descriptor() ([]byte, []int) {
	return file_billing_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLicenseResponse) GetStatusResponse() *g_common.StatusResponse {
	if x != nil {
		return x.StatusResponse
	}
	return nil
}

func (x *CreateLicenseResponse) GetLicense() *license.License {
	if x != nil {
		return x.License
	}
	return nil
}

type ReadLicensesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Licenses      []*license.License     `protobuf:"bytes,1,rep,name=licenses,proto3" json:"licenses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadLicensesResponse) Reset() {
	*x = ReadLicensesResponse{}
	mi := &file_billing_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadLicensesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadLicensesResponse) ProtoMessage() {}

func (x *ReadLicensesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadLicensesResponse.ProtoReflect.Descriptor instead.
func (*ReadLicensesResponse) Descriptor() ([]byte, []int) {
	return file_billing_service_proto_rawDescGZIP(), []int{2}
}

func (x *ReadLicensesResponse) GetLicenses() []*license.License {
	if x != nil {
		return x.Licenses
	}
	return nil
}

type UpdateLicenseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LicenseId     string                 `protobuf:"bytes,1,opt,name=licenseId,proto3" json:"licenseId,omitempty"`
	License       *license.License       `protobuf:"bytes,2,opt,name=license,proto3" json:"license,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLicenseRequest) Reset() {
	*x = UpdateLicenseRequest{}
	mi := &file_billing_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLicenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLicenseRequest) ProtoMessage() {}

func (x *UpdateLicenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLicenseRequest.ProtoReflect.Descriptor instead.
func (*UpdateLicenseRequest) Descriptor() ([]byte, []int) {
	return file_billing_service_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateLicenseRequest) GetLicenseId() string {
	if x != nil {
		return x.LicenseId
	}
	return ""
}

func (x *UpdateLicenseRequest) GetLicense() *license.License {
	if x != nil {
		return x.License
	}
	return nil
}

type DeleteLicenseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LicenseId     string                 `protobuf:"bytes,1,opt,name=licenseId,proto3" json:"licenseId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLicenseRequest) Reset() {
	*x = DeleteLicenseRequest{}
	mi := &file_billing_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLicenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLicenseRequest) ProtoMessage() {}

func (x *DeleteLicenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLicenseRequest.ProtoReflect.Descriptor instead.
func (*DeleteLicenseRequest) Descriptor() ([]byte, []int) {
	return file_billing_service_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteLicenseRequest) GetLicenseId() string {
	if x != nil {
		return x.LicenseId
	}
	return ""
}

type UpdatePaymentCustomerIdRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Provider          string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"` // "stripe", "pawapay", etc.
	PaymentCustomerId string                 `protobuf:"bytes,2,opt,name=paymentCustomerId,proto3" json:"paymentCustomerId,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdatePaymentCustomerIdRequest) Reset() {
	*x = UpdatePaymentCustomerIdRequest{}
	mi := &file_billing_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaymentCustomerIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaymentCustomerIdRequest) ProtoMessage() {}

func (x *UpdatePaymentCustomerIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaymentCustomerIdRequest.ProtoReflect.Descriptor instead.
func (*UpdatePaymentCustomerIdRequest) Descriptor() ([]byte, []int) {
	return file_billing_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePaymentCustomerIdRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *UpdatePaymentCustomerIdRequest) GetPaymentCustomerId() string {
	if x != nil {
		return x.PaymentCustomerId
	}
	return ""
}

type GetReferralInfoResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ReferralCode       string                 `protobuf:"bytes,1,opt,name=referralCode,proto3" json:"referralCode,omitempty"`
	CreditBalanceCents int32                  `protobuf:"varint,2,opt,name=creditBalanceCents,proto3" json:"creditBalanceCents,omitempty"`
	MinPayoutCents     int32                  `protobuf:"varint,3,opt,name=minPayoutCents,proto3" json:"minPayoutCents,omitempty"` // 1500 = €15
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetReferralInfoResponse) Reset() {
	*x = GetReferralInfoResponse{}
	mi := &file_billing_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReferralInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReferralInfoResponse) ProtoMessage() {}

func (x *GetReferralInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReferralInfoResponse.ProtoReflect.Descriptor instead.
func (*GetReferralInfoResponse) Descriptor() ([]byte, []int) {
	return file_billing_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetReferralInfoResponse) GetReferralCode() string {
	if x != nil {
		return x.ReferralCode
	}
	return ""
}

func (x *GetReferralInfoResponse) GetCreditBalanceCents() int32 {
	if x != nil {
		return x.CreditBalanceCents
	}
	return 0
}

func (x *GetReferralInfoResponse) GetMinPayoutCents() int32 {
	if x != nil {
		return x.MinPayoutCents
	}
	return 0
}

type RequestReferralPayoutResponse struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	StatusResponse *g_common.StatusResponse `protobuf:"bytes,1,opt,name=statusResponse,proto3" json:"statusResponse,omitempty"`
	AmountCents    int32                    `protobuf:"varint,2,opt,name=amountCents,proto3" json:"amountCents,omitempty"` // Amount requested for payout
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RequestReferralPayoutResponse) Reset() {
	*x = RequestReferralPayoutResponse{}
	mi := &file_billing_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestReferralPayoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestReferralPayoutResponse) ProtoMessage() {}

func (x *RequestReferralPayoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestReferralPayoutResponse.ProtoReflect.Descriptor instead.
func (*RequestReferralPayoutResponse) Descriptor() ([]byte, []int) {
	return file_billing_service_proto_rawDescGZIP(), []int{7}
}

func (x *RequestReferralPayoutResponse) GetStatusResponse() *g_common.StatusResponse {
	if x != nil {
		return x.StatusResponse
	}
	return nil
}

func (x *RequestReferralPayoutResponse) GetAmountCents() int32 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

type CreateCheckoutSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// / Stripe Price ID (from billing_products collection, e.g. readBillingProducts).
	PriceId string `protobuf:"bytes,1,opt,name=priceId,proto3" json:"priceId,omitempty"`
	// / URL to redirect after successful payment. May include {CHECKOUT_SESSION_ID}.
	SuccessUrl string `protobuf:"bytes,2,opt,name=successUrl,proto3" json:"successUrl,omitempty"`
	// / URL to redirect if customer cancels.
	CancelUrl string `protobuf:"bytes,3,opt,name=cancelUrl,proto3" json:"cancelUrl,omitempty"`
	// / Optional referral code to apply.
	ReferralCode string `protobuf:"bytes,4,opt,name=referralCode,proto3" json:"referralCode,omitempty"`
	// / Optional credit (cents) to apply. Deducted from firm balance.
	CreditAppliedCents int32 `protobuf:"varint,5,opt,name=creditAppliedCents,proto3" json:"creditAppliedCents,omitempty"`
	// / CGV / terms version the buyer accepted before checkout (YYYY-MM-DD, one revision per day).
	LegalTermsVersionDate string `protobuf:"bytes,6,opt,name=legalTermsVersionDate,proto3" json:"legalTermsVersionDate,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CreateCheckoutSessionRequest) Reset() {
	*x = CreateCheckoutSessionRequest{}
	mi := &file_billing_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCheckoutSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCheckoutSessionRequest) ProtoMessage() {}

func (x *CreateCheckoutSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCheckoutSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateCheckoutSessionRequest) Descriptor() ([]byte, []int) {
	return file_billing_service_proto_rawDescGZIP(), []int{8}
}

func (x *CreateCheckoutSessionRequest) GetPriceId() string {
	if x != nil {
		return x.PriceId
	}
	return ""
}

func (x *CreateCheckoutSessionRequest) GetSuccessUrl() string {
	if x != nil {
		return x.SuccessUrl
	}
	return ""
}

func (x *CreateCheckoutSessionRequest) GetCancelUrl() string {
	if x != nil {
		return x.CancelUrl
	}
	return ""
}

func (x *CreateCheckoutSessionRequest) GetReferralCode() string {
	if x != nil {
		return x.ReferralCode
	}
	return ""
}

func (x *CreateCheckoutSessionRequest) GetCreditAppliedCents() int32 {
	if x != nil {
		return x.CreditAppliedCents
	}
	return 0
}

func (x *CreateCheckoutSessionRequest) GetLegalTermsVersionDate() string {
	if x != nil {
		return x.LegalTermsVersionDate
	}
	return ""
}

type CreateCheckoutSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckoutUrl   string                 `protobuf:"bytes,1,opt,name=checkoutUrl,proto3" json:"checkoutUrl,omitempty"` // Redirect customer here
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCheckoutSessionResponse) Reset() {
	*x = CreateCheckoutSessionResponse{}
	mi := &file_billing_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCheckoutSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCheckoutSessionResponse) ProtoMessage() {}

func (x *CreateCheckoutSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCheckoutSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateCheckoutSessionResponse) Descriptor() ([]byte, []int) {
	return file_billing_service_proto_rawDescGZIP(), []int{9}
}

func (x *CreateCheckoutSessionResponse) GetCheckoutUrl() string {
	if x != nil {
		return x.CheckoutUrl
	}
	return ""
}

// / priceId is the single source of truth; billing_service maps it via billing_products collection.
type FulfillLicenseFromStripeRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	FirmId             string                 `protobuf:"bytes,1,opt,name=firmId,proto3" json:"firmId,omitempty"`
	LicenseId          string                 `protobuf:"bytes,2,opt,name=licenseId,proto3" json:"licenseId,omitempty"`
	PriceId            string                 `protobuf:"bytes,3,opt,name=priceId,proto3" json:"priceId,omitempty"` // Stripe price ID; billing_service looks up in billing_products
	StripeCustomerId   string                 `protobuf:"bytes,4,opt,name=stripeCustomerId,proto3" json:"stripeCustomerId,omitempty"`
	ReferralCode       string                 `protobuf:"bytes,5,opt,name=referralCode,proto3" json:"referralCode,omitempty"`
	CreditAppliedCents int32                  `protobuf:"varint,6,opt,name=creditAppliedCents,proto3" json:"creditAppliedCents,omitempty"`
	// / CGV / terms version from checkout session metadata (YYYY-MM-DD).
	LegalTermsVersionDate string `protobuf:"bytes,7,opt,name=legalTermsVersionDate,proto3" json:"legalTermsVersionDate,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *FulfillLicenseFromStripeRequest) Reset() {
	*x = FulfillLicenseFromStripeRequest{}
	mi := &file_billing_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FulfillLicenseFromStripeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FulfillLicenseFromStripeRequest) ProtoMessage() {}

func (x *FulfillLicenseFromStripeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FulfillLicenseFromStripeRequest.ProtoReflect.Descriptor instead.
func (*FulfillLicenseFromStripeRequest) Descriptor() ([]byte, []int) {
	return file_billing_service_proto_rawDescGZIP(), []int{10}
}

func (x *FulfillLicenseFromStripeRequest) GetFirmId() string {
	if x != nil {
		return x.FirmId
	}
	return ""
}

func (x *FulfillLicenseFromStripeRequest) GetLicenseId() string {
	if x != nil {
		return x.LicenseId
	}
	return ""
}

func (x *FulfillLicenseFromStripeRequest) GetPriceId() string {
	if x != nil {
		return x.PriceId
	}
	return ""
}

func (x *FulfillLicenseFromStripeRequest) GetStripeCustomerId() string {
	if x != nil {
		return x.StripeCustomerId
	}
	return ""
}

func (x *FulfillLicenseFromStripeRequest) GetReferralCode() string {
	if x != nil {
		return x.ReferralCode
	}
	return ""
}

func (x *FulfillLicenseFromStripeRequest) GetCreditAppliedCents() int32 {
	if x != nil {
		return x.CreditAppliedCents
	}
	return 0
}

func (x *FulfillLicenseFromStripeRequest) GetLegalTermsVersionDate() string {
	if x != nil {
		return x.LegalTermsVersionDate
	}
	return ""
}

// / Request to fulfill a license from a Stripe Checkout Session (e.g. after success redirect).
type FulfillFromStripeCheckoutSessionRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CheckoutSessionId string                 `protobuf:"bytes,1,opt,name=checkoutSessionId,proto3" json:"checkoutSessionId,omitempty"` // e.g. cs_xxx
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FulfillFromStripeCheckoutSessionRequest) Reset() {
	*x = FulfillFromStripeCheckoutSessionRequest{}
	mi := &file_billing_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FulfillFromStripeCheckoutSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FulfillFromStripeCheckoutSessionRequest) ProtoMessage() {}

func (x *FulfillFromStripeCheckoutSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FulfillFromStripeCheckoutSessionRequest.ProtoReflect.Descriptor instead.
func (*FulfillFromStripeCheckoutSessionRequest) Descriptor() ([]byte, []int) {
	return file_billing_service_proto_rawDescGZIP(), []int{11}
}

func (x *FulfillFromStripeCheckoutSessionRequest) GetCheckoutSessionId() string {
	if x != nil {
		return x.CheckoutSessionId
	}
	return ""
}

// / Billing product (license plan). Stored in billing_products collection.
// / Single source of truth for price mapping; replaces STRIPE_PRICE_* and STRIPE_PRODUCT_* env vars.
type BillingProduct struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProductId        string                 `protobuf:"bytes,1,opt,name=productId,proto3" json:"productId,omitempty"` // e.g. "solo", "trio", "pro"
	LicensePlan      license.LicensePlan    `protobuf:"varint,2,opt,name=licensePlan,proto3,enum=weebi.license.LicensePlan" json:"licensePlan,omitempty"`
	MaxUsers         int32                  `protobuf:"varint,3,opt,name=maxUsers,proto3" json:"maxUsers,omitempty"`
	AmountCents      int32                  `protobuf:"varint,4,opt,name=amountCents,proto3" json:"amountCents,omitempty"`
	Currency         string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	StripeProductId  string                 `protobuf:"bytes,6,opt,name=stripeProductId,proto3" json:"stripeProductId,omitempty"`
	StripePriceId    string                 `protobuf:"bytes,7,opt,name=stripePriceId,proto3" json:"stripePriceId,omitempty"`       // Used for checkout and webhook
	PawapayProductId string                 `protobuf:"bytes,8,opt,name=pawapayProductId,proto3" json:"pawapayProductId,omitempty"` // Optional, for future
	CreationDateUTC  *g_timestamp.Timestamp `protobuf:"bytes,9,opt,name=creationDateUTC,proto3" json:"creationDateUTC,omitempty"`
	UpdateDateUTC    *g_timestamp.Timestamp `protobuf:"bytes,10,opt,name=updateDateUTC,proto3" json:"updateDateUTC,omitempty"`
	DeletionDateUTC  *g_timestamp.Timestamp `protobuf:"bytes,11,opt,name=deletionDateUTC,proto3" json:"deletionDateUTC,omitempty"`
	IsDeleted        bool                   `protobuf:"varint,12,opt,name=isDeleted,proto3" json:"isDeleted,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BillingProduct) Reset() {
	*x = BillingProduct{}
	mi := &file_billing_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BillingProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillingProduct) ProtoMessage() {}

func (x *BillingProduct) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillingProduct.ProtoReflect.Descriptor instead.
func (*BillingProduct) Descriptor() ([]byte, []int) {
	return file_billing_service_proto_rawDescGZIP(), []int{12}
}

func (x *BillingProduct) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *BillingProduct) GetLicensePlan() license.LicensePlan {
	if x != nil {
		return x.LicensePlan
	}
	return license.LicensePlan(0)
}

func (x *BillingProduct) GetMaxUsers() int32 {
	if x != nil {
		return x.MaxUsers
	}
	return 0
}

func (x *BillingProduct) GetAmountCents() int32 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *BillingProduct) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *BillingProduct) GetStripeProductId() string {
	if x != nil {
		return x.StripeProductId
	}
	return ""
}

func (x *BillingProduct) GetStripePriceId() string {
	if x != nil {
		return x.StripePriceId
	}
	return ""
}

func (x *BillingProduct) GetPawapayProductId() string {
	if x != nil {
		return x.PawapayProductId
	}
	return ""
}

func (x *BillingProduct) GetCreationDateUTC() *g_timestamp.Timestamp {
	if x != nil {
		return x.CreationDateUTC
	}
	return nil
}

func (x *BillingProduct) GetUpdateDateUTC() *g_timestamp.Timestamp {
	if x != nil {
		return x.UpdateDateUTC
	}
	return nil
}

func (x *BillingProduct) GetDeletionDateUTC() *g_timestamp.Timestamp {
	if x != nil {
		return x.DeletionDateUTC
	}
	return nil
}

func (x *BillingProduct) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

type ReadBillingProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*BillingProduct      `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadBillingProductsResponse) Reset() {
	*x = ReadBillingProductsResponse{}
	mi := &file_billing_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadBillingProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadBillingProductsResponse) ProtoMessage() {}

func (x *ReadBillingProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadBillingProductsResponse.ProtoReflect.Descriptor instead.
func (*ReadBillingProductsResponse) Descriptor() ([]byte, []int) {
	return file_billing_service_proto_rawDescGZIP(), []int{13}
}

func (x *ReadBillingProductsResponse) GetProducts() []*BillingProduct {
	if x != nil {
		return x.Products
	}
	return nil
}

var File_billing_service_proto protoreflect.FileDescriptor

const file_billing_service_proto_rawDesc = "" +
	"\n" +
	"\x15billing_service.proto\x12\x15weebi.billing.service\x1a\x12common/empty.proto\x1a\x15common/g_common.proto\x1a\x18common/g_timestamp.proto\x1a\rlicense.proto\"\x9c\x01\n" +
	"\x14CreateLicenseRequest\x120\n" +
	"\alicense\x18\x01 \x01(\v2\x16.weebi.license.LicenseR\alicense\x12\"\n" +
	"\freferralCode\x18\x02 \x01(\tR\freferralCode\x12.\n" +
	"\x12creditAppliedCents\x18\x03 \x01(\x05R\x12creditAppliedCents\"\x97\x01\n" +
	"\x15CreateLicenseResponse\x12L\n" +
	"\x0estatusResponse\x18\x01 \x01(\v2$.google.retail.common.StatusResponseR\x0estatusResponse\x120\n" +
	"\alicense\x18\x02 \x01(\v2\x16.weebi.license.LicenseR\alicense\"J\n" +
	"\x14ReadLicensesResponse\x122\n" +
	"\blicenses\x18\x01 \x03(\v2\x16.weebi.license.LicenseR\blicenses\"f\n" +
	"\x14UpdateLicenseRequest\x12\x1c\n" +
	"\tlicenseId\x18\x01 \x01(\tR\tlicenseId\x120\n" +
	"\alicense\x18\x02 \x01(\v2\x16.weebi.license.LicenseR\alicense\"4\n" +
	"\x14DeleteLicenseRequest\x12\x1c\n" +
	"\tlicenseId\x18\x01 \x01(\tR\tlicenseId\"j\n" +
	"\x1eUpdatePaymentCustomerIdRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12,\n" +
	"\x11paymentCustomerId\x18\x02 \x01(\tR\x11paymentCustomerId\"\x95\x01\n" +
	"\x17GetReferralInfoResponse\x12\"\n" +
	"\freferralCode\x18\x01 \x01(\tR\freferralCode\x12.\n" +
	"\x12creditBalanceCents\x18\x02 \x01(\x05R\x12creditBalanceCents\x12&\n" +
	"\x0eminPayoutCents\x18\x03 \x01(\x05R\x0eminPayoutCents\"\x8f\x01\n" +
	"\x1dRequestReferralPayoutResponse\x12L\n" +
	"\x0estatusResponse\x18\x01 \x01(\v2$.google.retail.common.StatusResponseR\x0estatusResponse\x12 \n" +
	"\vamountCents\x18\x02 \x01(\x05R\vamountCents\"\x80\x02\n" +
	"\x1cCreateCheckoutSessionRequest\x12\x18\n" +
	"\apriceId\x18\x01 \x01(\tR\apriceId\x12\x1e\n" +
	"\n" +
	"successUrl\x18\x02 \x01(\tR\n" +
	"successUrl\x12\x1c\n" +
	"\tcancelUrl\x18\x03 \x01(\tR\tcancelUrl\x12\"\n" +
	"\freferralCode\x18\x04 \x01(\tR\freferralCode\x12.\n" +
	"\x12creditAppliedCents\x18\x05 \x01(\x05R\x12creditAppliedCents\x124\n" +
	"\x15legalTermsVersionDate\x18\x06 \x01(\tR\x15legalTermsVersionDate\"A\n" +
	"\x1dCreateCheckoutSessionResponse\x12 \n" +
	"\vcheckoutUrl\x18\x01 \x01(\tR\vcheckoutUrl\"\xa7\x02\n" +
	"\x1fFulfillLicenseFromStripeRequest\x12\x16\n" +
	"\x06firmId\x18\x01 \x01(\tR\x06firmId\x12\x1c\n" +
	"\tlicenseId\x18\x02 \x01(\tR\tlicenseId\x12\x18\n" +
	"\apriceId\x18\x03 \x01(\tR\apriceId\x12*\n" +
	"\x10stripeCustomerId\x18\x04 \x01(\tR\x10stripeCustomerId\x12\"\n" +
	"\freferralCode\x18\x05 \x01(\tR\freferralCode\x12.\n" +
	"\x12creditAppliedCents\x18\x06 \x01(\x05R\x12creditAppliedCents\x124\n" +
	"\x15legalTermsVersionDate\x18\a \x01(\tR\x15legalTermsVersionDate\"W\n" +
	"'FulfillFromStripeCheckoutSessionRequest\x12,\n" +
	"\x11checkoutSessionId\x18\x01 \x01(\tR\x11checkoutSessionId\"\xae\x04\n" +
	"\x0eBillingProduct\x12\x1c\n" +
	"\tproductId\x18\x01 \x01(\tR\tproductId\x12<\n" +
	"\vlicensePlan\x18\x02 \x01(\x0e2\x1a.weebi.license.LicensePlanR\vlicensePlan\x12\x1a\n" +
	"\bmaxUsers\x18\x03 \x01(\x05R\bmaxUsers\x12 \n" +
	"\vamountCents\x18\x04 \x01(\x05R\vamountCents\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12(\n" +
	"\x0fstripeProductId\x18\x06 \x01(\tR\x0fstripeProductId\x12$\n" +
	"\rstripePriceId\x18\a \x01(\tR\rstripePriceId\x12*\n" +
	"\x10pawapayProductId\x18\b \x01(\tR\x10pawapayProductId\x12D\n" +
	"\x0fcreationDateUTC\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x0fcreationDateUTC\x12@\n" +
	"\rupdateDateUTC\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\rupdateDateUTC\x12D\n" +
	"\x0fdeletionDateUTC\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x0fdeletionDateUTC\x12\x1c\n" +
	"\tisDeleted\x18\f \x01(\bR\tisDeleted\"`\n" +
	"\x1bReadBillingProductsResponse\x12A\n" +
	"\bproducts\x18\x01 \x03(\v2%.weebi.billing.service.BillingProductR\bproducts2\xdd\t\n" +
	"\x0eBillingService\x12j\n" +
	"\rcreateLicense\x12+.weebi.billing.service.CreateLicenseRequest\x1a,.weebi.billing.service.CreateLicenseResponse\x12V\n" +
	"\freadLicenses\x12\x19.weebi.common.empty.Empty\x1a+.weebi.billing.service.ReadLicensesResponse\x12d\n" +
	"\x13readBillingProducts\x12\x19.weebi.common.empty.Empty\x1a2.weebi.billing.service.ReadBillingProductsResponse\x12b\n" +
	"\rupdateLicense\x12+.weebi.billing.service.UpdateLicenseRequest\x1a$.google.retail.common.StatusResponse\x12b\n" +
	"\rdeleteLicense\x12+.weebi.billing.service.DeleteLicenseRequest\x1a$.google.retail.common.StatusResponse\x12v\n" +
	"\x17updatePaymentCustomerId\x125.weebi.billing.service.UpdatePaymentCustomerIdRequest\x1a$.google.retail.common.StatusResponse\x12\\\n" +
	"\x0fgetReferralInfo\x12\x19.weebi.common.empty.Empty\x1a..weebi.billing.service.GetReferralInfoResponse\x12h\n" +
	"\x15requestReferralPayout\x12\x19.weebi.common.empty.Empty\x1a4.weebi.billing.service.RequestReferralPayoutResponse\x12\x82\x01\n" +
	"\x15createCheckoutSession\x123.weebi.billing.service.CreateCheckoutSessionRequest\x1a4.weebi.billing.service.CreateCheckoutSessionResponse\x12\x80\x01\n" +
	"\x18fulfillLicenseFromStripe\x126.weebi.billing.service.FulfillLicenseFromStripeRequest\x1a,.weebi.billing.service.CreateLicenseResponse\x12\x90\x01\n" +
	" fulfillFromStripeCheckoutSession\x12>.weebi.billing.service.FulfillFromStripeCheckoutSessionRequest\x1a,.weebi.billing.service.CreateLicenseResponseb\x06proto3"

var (
	file_billing_service_proto_rawDescOnce sync.Once
	file_billing_service_proto_rawDescData []byte
)

func file_billing_service_proto_rawDescGZIP() []byte {
	file_billing_service_proto_rawDescOnce.Do(func() {
		file_billing_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_billing_service_proto_rawDesc), len(file_billing_service_proto_rawDesc)))
	})
	return file_billing_service_proto_rawDescData
}

var file_billing_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_billing_service_proto_goTypes = []any{
	(*CreateLicenseRequest)(nil),                    // 0: weebi.billing.service.CreateLicenseRequest
	(*CreateLicenseResponse)(nil),                   // 1: weebi.billing.service.CreateLicenseResponse
	(*ReadLicensesResponse)(nil),                    // 2: weebi.billing.service.ReadLicensesResponse
	(*UpdateLicenseRequest)(nil),                    // 3: weebi.billing.service.UpdateLicenseRequest
	(*DeleteLicenseRequest)(nil),                    // 4: weebi.billing.service.DeleteLicenseRequest
	(*UpdatePaymentCustomerIdRequest)(nil),          // 5: weebi.billing.service.UpdatePaymentCustomerIdRequest
	(*GetReferralInfoResponse)(nil),                 // 6: weebi.billing.service.GetReferralInfoResponse
	(*RequestReferralPayoutResponse)(nil),           // 7: weebi.billing.service.RequestReferralPayoutResponse
	(*CreateCheckoutSessionRequest)(nil),            // 8: weebi.billing.service.CreateCheckoutSessionRequest
	(*CreateCheckoutSessionResponse)(nil),           // 9: weebi.billing.service.CreateCheckoutSessionResponse
	(*FulfillLicenseFromStripeRequest)(nil),         // 10: weebi.billing.service.FulfillLicenseFromStripeRequest
	(*FulfillFromStripeCheckoutSessionRequest)(nil), // 11: weebi.billing.service.FulfillFromStripeCheckoutSessionRequest
	(*BillingProduct)(nil),                          // 12: weebi.billing.service.BillingProduct
	(*ReadBillingProductsResponse)(nil),             // 13: weebi.billing.service.ReadBillingProductsResponse
	(*license.License)(nil),                         // 14: weebi.license.License
	(*g_common.StatusResponse)(nil),                 // 15: google.retail.common.StatusResponse
	(license.LicensePlan)(0),                        // 16: weebi.license.LicensePlan
	(*g_timestamp.Timestamp)(nil),                   // 17: google.protobuf.Timestamp
	(*empty.Empty)(nil),                             // 18: weebi.common.empty.Empty
}
var file_billing_service_proto_depIdxs = []int32{
	14, // 0: weebi.billing.service.CreateLicenseRequest.license:type_name -> weebi.license.License
	15, // 1: weebi.billing.service.CreateLicenseResponse.statusResponse:type_name -> google.retail.common.StatusResponse
	14, // 2: weebi.billing.service.CreateLicenseResponse.license:type_name -> weebi.license.License
	14, // 3: weebi.billing.service.ReadLicensesResponse.licenses:type_name -> weebi.license.License
	14, // 4: weebi.billing.service.UpdateLicenseRequest.license:type_name -> weebi.license.License
	15, // 5: weebi.billing.service.RequestReferralPayoutResponse.statusResponse:type_name -> google.retail.common.StatusResponse
	16, // 6: weebi.billing.service.BillingProduct.licensePlan:type_name -> weebi.license.LicensePlan
	17, // 7: weebi.billing.service.BillingProduct.creationDateUTC:type_name -> google.protobuf.Timestamp
	17, // 8: weebi.billing.service.BillingProduct.updateDateUTC:type_name -> google.protobuf.Timestamp
	17, // 9: weebi.billing.service.BillingProduct.deletionDateUTC:type_name -> google.protobuf.Timestamp
	12, // 10: weebi.billing.service.ReadBillingProductsResponse.products:type_name -> weebi.billing.service.BillingProduct
	0,  // 11: weebi.billing.service.BillingService.createLicense:input_type -> weebi.billing.service.CreateLicenseRequest
	18, // 12: weebi.billing.service.BillingService.readLicenses:input_type -> weebi.common.empty.Empty
	18, // 13: weebi.billing.service.BillingService.readBillingProducts:input_type -> weebi.common.empty.Empty
	3,  // 14: weebi.billing.service.BillingService.updateLicense:input_type -> weebi.billing.service.UpdateLicenseRequest
	4,  // 15: weebi.billing.service.BillingService.deleteLicense:input_type -> weebi.billing.service.DeleteLicenseRequest
	5,  // 16: weebi.billing.service.BillingService.updatePaymentCustomerId:input_type -> weebi.billing.service.UpdatePaymentCustomerIdRequest
	18, // 17: weebi.billing.service.BillingService.getReferralInfo:input_type -> weebi.common.empty.Empty
	18, // 18: weebi.billing.service.BillingService.requestReferralPayout:input_type -> weebi.common.empty.Empty
	8,  // 19: weebi.billing.service.BillingService.createCheckoutSession:input_type -> weebi.billing.service.CreateCheckoutSessionRequest
	10, // 20: weebi.billing.service.BillingService.fulfillLicenseFromStripe:input_type -> weebi.billing.service.FulfillLicenseFromStripeRequest
	11, // 21: weebi.billing.service.BillingService.fulfillFromStripeCheckoutSession:input_type -> weebi.billing.service.FulfillFromStripeCheckoutSessionRequest
	1,  // 22: weebi.billing.service.BillingService.createLicense:output_type -> weebi.billing.service.CreateLicenseResponse
	2,  // 23: weebi.billing.service.BillingService.readLicenses:output_type -> weebi.billing.service.ReadLicensesResponse
	13, // 24: weebi.billing.service.BillingService.readBillingProducts:output_type -> weebi.billing.service.ReadBillingProductsResponse
	15, // 25: weebi.billing.service.BillingService.updateLicense:output_type -> google.retail.common.StatusResponse
	15, // 26: weebi.billing.service.BillingService.deleteLicense:output_type -> google.retail.common.StatusResponse
	15, // 27: weebi.billing.service.BillingService.updatePaymentCustomerId:output_type -> google.retail.common.StatusResponse
	6,  // 28: weebi.billing.service.BillingService.getReferralInfo:output_type -> weebi.billing.service.GetReferralInfoResponse
	7,  // 29: weebi.billing.service.BillingService.requestReferralPayout:output_type -> weebi.billing.service.RequestReferralPayoutResponse
	9,  // 30: weebi.billing.service.BillingService.createCheckoutSession:output_type -> weebi.billing.service.CreateCheckoutSessionResponse
	1,  // 31: weebi.billing.service.BillingService.fulfillLicenseFromStripe:output_type -> weebi.billing.service.CreateLicenseResponse
	1,  // 32: weebi.billing.service.BillingService.fulfillFromStripeCheckoutSession:output_type -> weebi.billing.service.CreateLicenseResponse
	22, // [22:33] is the sub-list for method output_type
	11, // [11:22] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_billing_service_proto_init() }
func file_billing_service_proto_init() {
	if File_billing_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_billing_service_proto_rawDesc), len(file_billing_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_billing_service_proto_goTypes,
		DependencyIndexes: file_billing_service_proto_depIdxs,
		MessageInfos:      file_billing_service_proto_msgTypes,
	}.Build()
	File_billing_service_proto = out.File
	file_billing_service_proto_goTypes = nil
	file_billing_service_proto_depIdxs = nil
}
