// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: billing_service.proto

package service

import (
	context "context"
	empty "github.com/weebi-com/protos/common/empty"
	g_common "github.com/weebi-com/protos/common/g_common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BillingService_CreateLicense_FullMethodName                    = "/weebi.billing.service.BillingService/createLicense"
	BillingService_ReadLicenses_FullMethodName                     = "/weebi.billing.service.BillingService/readLicenses"
	BillingService_ReadBillingProducts_FullMethodName              = "/weebi.billing.service.BillingService/readBillingProducts"
	BillingService_UpdateLicense_FullMethodName                    = "/weebi.billing.service.BillingService/updateLicense"
	BillingService_DeleteLicense_FullMethodName                    = "/weebi.billing.service.BillingService/deleteLicense"
	BillingService_UpdatePaymentCustomerId_FullMethodName          = "/weebi.billing.service.BillingService/updatePaymentCustomerId"
	BillingService_GetReferralInfo_FullMethodName                  = "/weebi.billing.service.BillingService/getReferralInfo"
	BillingService_RequestReferralPayout_FullMethodName            = "/weebi.billing.service.BillingService/requestReferralPayout"
	BillingService_CreateCheckoutSession_FullMethodName            = "/weebi.billing.service.BillingService/createCheckoutSession"
	BillingService_FulfillLicenseFromStripe_FullMethodName         = "/weebi.billing.service.BillingService/fulfillLicenseFromStripe"
	BillingService_FulfillFromStripeCheckoutSession_FullMethodName = "/weebi.billing.service.BillingService/fulfillFromStripeCheckoutSession"
)

// BillingServiceClient is the client API for BillingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// / License CRUD and payment handling. Operates on Firm.licenses (embedded).
// / firmId is derived from the authenticated user's context.
type BillingServiceClient interface {
	// / Create a license and append to firm.licenses.
	CreateLicense(ctx context.Context, in *CreateLicenseRequest, opts ...grpc.CallOption) (*CreateLicenseResponse, error)
	// / Read all licenses for the user's firm.
	ReadLicenses(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ReadLicensesResponse, error)
	// / Read available billing products (license plans). Used by webapp for checkout.
	ReadBillingProducts(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ReadBillingProductsResponse, error)
	// / Update an existing license by licenseId.
	UpdateLicense(ctx context.Context, in *UpdateLicenseRequest, opts ...grpc.CallOption) (*g_common.StatusResponse, error)
	// / Remove a license from firm.licenses.
	DeleteLicense(ctx context.Context, in *DeleteLicenseRequest, opts ...grpc.CallOption) (*g_common.StatusResponse, error)
	// / Set the customer ID for a payment provider on the firm.
	UpdatePaymentCustomerId(ctx context.Context, in *UpdatePaymentCustomerIdRequest, opts ...grpc.CallOption) (*g_common.StatusResponse, error)
	// / Get referral code and credit balance for the user's firm.
	GetReferralInfo(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetReferralInfoResponse, error)
	// / Request cash-out of referral credit. Requires balance >= 1500 (€15). Payout to same payment customer.
	RequestReferralPayout(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*RequestReferralPayoutResponse, error)
	// / Create a Stripe Checkout Session for a license purchase. Returns URL to redirect the customer.
	CreateCheckoutSession(ctx context.Context, in *CreateCheckoutSessionRequest, opts ...grpc.CallOption) (*CreateCheckoutSessionResponse, error)
	// / Internal: fulfill a license after Stripe payment. Called by weebi_express webhook handler.
	// / Requires service account auth.
	FulfillLicenseFromStripe(ctx context.Context, in *FulfillLicenseFromStripeRequest, opts ...grpc.CallOption) (*CreateLicenseResponse, error)
	// / User-facing: ensure license is created from a paid Checkout Session (e.g. after redirect).
	// / Use when webhook may have failed or not yet run. Idempotent; validates session belongs to user's firm.
	FulfillFromStripeCheckoutSession(ctx context.Context, in *FulfillFromStripeCheckoutSessionRequest, opts ...grpc.CallOption) (*CreateLicenseResponse, error)
}

type billingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBillingServiceClient(cc grpc.ClientConnInterface) BillingServiceClient {
	return &billingServiceClient{cc}
}

func (c *billingServiceClient) CreateLicense(ctx context.Context, in *CreateLicenseRequest, opts ...grpc.CallOption) (*CreateLicenseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLicenseResponse)
	err := c.cc.Invoke(ctx, BillingService_CreateLicense_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) ReadLicenses(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ReadLicensesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadLicensesResponse)
	err := c.cc.Invoke(ctx, BillingService_ReadLicenses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) ReadBillingProducts(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ReadBillingProductsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadBillingProductsResponse)
	err := c.cc.Invoke(ctx, BillingService_ReadBillingProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) UpdateLicense(ctx context.Context, in *UpdateLicenseRequest, opts ...grpc.CallOption) (*g_common.StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(g_common.StatusResponse)
	err := c.cc.Invoke(ctx, BillingService_UpdateLicense_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) DeleteLicense(ctx context.Context, in *DeleteLicenseRequest, opts ...grpc.CallOption) (*g_common.StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(g_common.StatusResponse)
	err := c.cc.Invoke(ctx, BillingService_DeleteLicense_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) UpdatePaymentCustomerId(ctx context.Context, in *UpdatePaymentCustomerIdRequest, opts ...grpc.CallOption) (*g_common.StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(g_common.StatusResponse)
	err := c.cc.Invoke(ctx, BillingService_UpdatePaymentCustomerId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) GetReferralInfo(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetReferralInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReferralInfoResponse)
	err := c.cc.Invoke(ctx, BillingService_GetReferralInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) RequestReferralPayout(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*RequestReferralPayoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestReferralPayoutResponse)
	err := c.cc.Invoke(ctx, BillingService_RequestReferralPayout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) CreateCheckoutSession(ctx context.Context, in *CreateCheckoutSessionRequest, opts ...grpc.CallOption) (*CreateCheckoutSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCheckoutSessionResponse)
	err := c.cc.Invoke(ctx, BillingService_CreateCheckoutSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) FulfillLicenseFromStripe(ctx context.Context, in *FulfillLicenseFromStripeRequest, opts ...grpc.CallOption) (*CreateLicenseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLicenseResponse)
	err := c.cc.Invoke(ctx, BillingService_FulfillLicenseFromStripe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) FulfillFromStripeCheckoutSession(ctx context.Context, in *FulfillFromStripeCheckoutSessionRequest, opts ...grpc.CallOption) (*CreateLicenseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLicenseResponse)
	err := c.cc.Invoke(ctx, BillingService_FulfillFromStripeCheckoutSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BillingServiceServer is the server API for BillingService service.
// All implementations must embed UnimplementedBillingServiceServer
// for forward compatibility.
//
// / License CRUD and payment handling. Operates on Firm.licenses (embedded).
// / firmId is derived from the authenticated user's context.
type BillingServiceServer interface {
	// / Create a license and append to firm.licenses.
	CreateLicense(context.Context, *CreateLicenseRequest) (*CreateLicenseResponse, error)
	// / Read all licenses for the user's firm.
	ReadLicenses(context.Context, *empty.Empty) (*ReadLicensesResponse, error)
	// / Read available billing products (license plans). Used by webapp for checkout.
	ReadBillingProducts(context.Context, *empty.Empty) (*ReadBillingProductsResponse, error)
	// / Update an existing license by licenseId.
	UpdateLicense(context.Context, *UpdateLicenseRequest) (*g_common.StatusResponse, error)
	// / Remove a license from firm.licenses.
	DeleteLicense(context.Context, *DeleteLicenseRequest) (*g_common.StatusResponse, error)
	// / Set the customer ID for a payment provider on the firm.
	UpdatePaymentCustomerId(context.Context, *UpdatePaymentCustomerIdRequest) (*g_common.StatusResponse, error)
	// / Get referral code and credit balance for the user's firm.
	GetReferralInfo(context.Context, *empty.Empty) (*GetReferralInfoResponse, error)
	// / Request cash-out of referral credit. Requires balance >= 1500 (€15). Payout to same payment customer.
	RequestReferralPayout(context.Context, *empty.Empty) (*RequestReferralPayoutResponse, error)
	// / Create a Stripe Checkout Session for a license purchase. Returns URL to redirect the customer.
	CreateCheckoutSession(context.Context, *CreateCheckoutSessionRequest) (*CreateCheckoutSessionResponse, error)
	// / Internal: fulfill a license after Stripe payment. Called by weebi_express webhook handler.
	// / Requires service account auth.
	FulfillLicenseFromStripe(context.Context, *FulfillLicenseFromStripeRequest) (*CreateLicenseResponse, error)
	// / User-facing: ensure license is created from a paid Checkout Session (e.g. after redirect).
	// / Use when webhook may have failed or not yet run. Idempotent; validates session belongs to user's firm.
	FulfillFromStripeCheckoutSession(context.Context, *FulfillFromStripeCheckoutSessionRequest) (*CreateLicenseResponse, error)
	mustEmbedUnimplementedBillingServiceServer()
}

// UnimplementedBillingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBillingServiceServer struct{}

func (UnimplementedBillingServiceServer) CreateLicense(context.Context, *CreateLicenseRequest) (*CreateLicenseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLicense not implemented")
}
func (UnimplementedBillingServiceServer) ReadLicenses(context.Context, *empty.Empty) (*ReadLicensesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadLicenses not implemented")
}
func (UnimplementedBillingServiceServer) ReadBillingProducts(context.Context, *empty.Empty) (*ReadBillingProductsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadBillingProducts not implemented")
}
func (UnimplementedBillingServiceServer) UpdateLicense(context.Context, *UpdateLicenseRequest) (*g_common.StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLicense not implemented")
}
func (UnimplementedBillingServiceServer) DeleteLicense(context.Context, *DeleteLicenseRequest) (*g_common.StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLicense not implemented")
}
func (UnimplementedBillingServiceServer) UpdatePaymentCustomerId(context.Context, *UpdatePaymentCustomerIdRequest) (*g_common.StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePaymentCustomerId not implemented")
}
func (UnimplementedBillingServiceServer) GetReferralInfo(context.Context, *empty.Empty) (*GetReferralInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReferralInfo not implemented")
}
func (UnimplementedBillingServiceServer) RequestReferralPayout(context.Context, *empty.Empty) (*RequestReferralPayoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestReferralPayout not implemented")
}
func (UnimplementedBillingServiceServer) CreateCheckoutSession(context.Context, *CreateCheckoutSessionRequest) (*CreateCheckoutSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCheckoutSession not implemented")
}
func (UnimplementedBillingServiceServer) FulfillLicenseFromStripe(context.Context, *FulfillLicenseFromStripeRequest) (*CreateLicenseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FulfillLicenseFromStripe not implemented")
}
func (UnimplementedBillingServiceServer) FulfillFromStripeCheckoutSession(context.Context, *FulfillFromStripeCheckoutSessionRequest) (*CreateLicenseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FulfillFromStripeCheckoutSession not implemented")
}
func (UnimplementedBillingServiceServer) mustEmbedUnimplementedBillingServiceServer() {}
func (UnimplementedBillingServiceServer) testEmbeddedByValue()                        {}

// UnsafeBillingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BillingServiceServer will
// result in compilation errors.
type UnsafeBillingServiceServer interface {
	mustEmbedUnimplementedBillingServiceServer()
}

func RegisterBillingServiceServer(s grpc.ServiceRegistrar, srv BillingServiceServer) {
	// If the following call pancis, it indicates UnimplementedBillingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BillingService_ServiceDesc, srv)
}

func _BillingService_CreateLicense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLicenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).CreateLicense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_CreateLicense_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).CreateLicense(ctx, req.(*CreateLicenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_ReadLicenses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).ReadLicenses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_ReadLicenses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).ReadLicenses(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_ReadBillingProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).ReadBillingProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_ReadBillingProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).ReadBillingProducts(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_UpdateLicense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLicenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).UpdateLicense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_UpdateLicense_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).UpdateLicense(ctx, req.(*UpdateLicenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_DeleteLicense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLicenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).DeleteLicense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_DeleteLicense_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).DeleteLicense(ctx, req.(*DeleteLicenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_UpdatePaymentCustomerId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePaymentCustomerIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).UpdatePaymentCustomerId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_UpdatePaymentCustomerId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).UpdatePaymentCustomerId(ctx, req.(*UpdatePaymentCustomerIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_GetReferralInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).GetReferralInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_GetReferralInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).GetReferralInfo(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_RequestReferralPayout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).RequestReferralPayout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_RequestReferralPayout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).RequestReferralPayout(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_CreateCheckoutSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCheckoutSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).CreateCheckoutSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_CreateCheckoutSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).CreateCheckoutSession(ctx, req.(*CreateCheckoutSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_FulfillLicenseFromStripe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FulfillLicenseFromStripeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).FulfillLicenseFromStripe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_FulfillLicenseFromStripe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).FulfillLicenseFromStripe(ctx, req.(*FulfillLicenseFromStripeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_FulfillFromStripeCheckoutSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FulfillFromStripeCheckoutSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).FulfillFromStripeCheckoutSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_FulfillFromStripeCheckoutSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).FulfillFromStripeCheckoutSession(ctx, req.(*FulfillFromStripeCheckoutSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BillingService_ServiceDesc is the grpc.ServiceDesc for BillingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BillingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weebi.billing.service.BillingService",
	HandlerType: (*BillingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "createLicense",
			Handler:    _BillingService_CreateLicense_Handler,
		},
		{
			MethodName: "readLicenses",
			Handler:    _BillingService_ReadLicenses_Handler,
		},
		{
			MethodName: "readBillingProducts",
			Handler:    _BillingService_ReadBillingProducts_Handler,
		},
		{
			MethodName: "updateLicense",
			Handler:    _BillingService_UpdateLicense_Handler,
		},
		{
			MethodName: "deleteLicense",
			Handler:    _BillingService_DeleteLicense_Handler,
		},
		{
			MethodName: "updatePaymentCustomerId",
			Handler:    _BillingService_UpdatePaymentCustomerId_Handler,
		},
		{
			MethodName: "getReferralInfo",
			Handler:    _BillingService_GetReferralInfo_Handler,
		},
		{
			MethodName: "requestReferralPayout",
			Handler:    _BillingService_RequestReferralPayout_Handler,
		},
		{
			MethodName: "createCheckoutSession",
			Handler:    _BillingService_CreateCheckoutSession_Handler,
		},
		{
			MethodName: "fulfillLicenseFromStripe",
			Handler:    _BillingService_FulfillLicenseFromStripe_Handler,
		},
		{
			MethodName: "fulfillFromStripeCheckoutSession",
			Handler:    _BillingService_FulfillFromStripeCheckoutSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "billing_service.proto",
}
