// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: firm.proto

package firm

import (
	g_common "github.com/weebi-com/protos/common/g_common"
	license "github.com/weebi-com/protos/license"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Firm struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	FirmId string                 `protobuf:"bytes,1,opt,name=firmId,proto3" json:"firmId,omitempty"`
	Name   string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// / @deprecated Use licenses instead.
	//
	// Deprecated: Marked as deprecated in firm.proto.
	SubscriptionPlan string `protobuf:"bytes,3,opt,name=subscriptionPlan,proto3" json:"subscriptionPlan,omitempty"`
	// / @deprecated Use licenses[].maxUsers instead.
	//
	// Deprecated: Marked as deprecated in firm.proto.
	SubscriptionSeats int32 `protobuf:"varint,4,opt,name=subscriptionSeats,proto3" json:"subscriptionSeats,omitempty"` //  1 seat == 1 user/device
	// / @deprecated Use licenses[].validFrom instead.
	//
	// Deprecated: Marked as deprecated in firm.proto.
	SubscriptionStartTimestampUTC *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=subscriptionStartTimestampUTC,proto3" json:"subscriptionStartTimestampUTC,omitempty"`
	// / @deprecated Use licenses[].validUntil and LicenseSeat.validUntil instead.
	//
	// Deprecated: Marked as deprecated in firm.proto.
	SubscriptionEndTimestampUTC *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=subscriptionEndTimestampUTC,proto3" json:"subscriptionEndTimestampUTC,omitempty"`
	Status                      bool                   `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	StatusUpdateTimestampUTC    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=statusUpdateTimestampUTC,proto3" json:"statusUpdateTimestampUTC,omitempty"` //if weebi disables date will be in UTC time not local
	LastUpdateTimestampUTC      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=lastUpdateTimestampUTC,proto3" json:"lastUpdateTimestampUTC,omitempty"`
	LastUpdatedByuserId         string                 `protobuf:"bytes,10,opt,name=lastUpdatedByuserId,proto3" json:"lastUpdatedByuserId,omitempty"`
	IsMailVerified              bool                   `protobuf:"varint,11,opt,name=isMailVerified,proto3" json:"isMailVerified,omitempty"`
	CreationDateUTC             *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=creationDateUTC,proto3" json:"creationDateUTC,omitempty"`
	StripeCustomerId            string                 `protobuf:"bytes,13,opt,name=stripeCustomerId,proto3" json:"stripeCustomerId,omitempty"`
	// / Active licenses. A firm can have multiple licenses (e.g. add-ons, renewals).
	Licenses []*license.License `protobuf:"bytes,14,rep,name=licenses,proto3" json:"licenses,omitempty"`
	// / Customer IDs per payment provider. Keys: "stripe", "pawapay", etc.
	ProviderCustomerIds map[string]string `protobuf:"bytes,15,rep,name=providerCustomerIds,proto3" json:"providerCustomerIds,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// / Per-firm referral code. Share with others; 20% commission on referred license sales.
	ReferralCode string `protobuf:"bytes,16,opt,name=referralCode,proto3" json:"referralCode,omitempty"`
	// / Referral credit balance in EUR cents. Auto-applied at checkout or cash-out above €15.
	ReferralCreditBalanceCents int32 `protobuf:"varint,17,opt,name=referralCreditBalanceCents,proto3" json:"referralCreditBalanceCents,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *Firm) Reset() {
	*x = Firm{}
	mi := &file_firm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Firm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Firm) ProtoMessage() {}

func (x *Firm) ProtoReflect() protoreflect.Message {
	mi := &file_firm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Firm.ProtoReflect.Descriptor instead.
func (*Firm) Descriptor() ([]byte, []int) {
	return file_firm_proto_rawDescGZIP(), []int{0}
}

func (x *Firm) GetFirmId() string {
	if x != nil {
		return x.FirmId
	}
	return ""
}

func (x *Firm) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Deprecated: Marked as deprecated in firm.proto.
func (x *Firm) GetSubscriptionPlan() string {
	if x != nil {
		return x.SubscriptionPlan
	}
	return ""
}

// Deprecated: Marked as deprecated in firm.proto.
func (x *Firm) GetSubscriptionSeats() int32 {
	if x != nil {
		return x.SubscriptionSeats
	}
	return 0
}

// Deprecated: Marked as deprecated in firm.proto.
func (x *Firm) GetSubscriptionStartTimestampUTC() *timestamppb.Timestamp {
	if x != nil {
		return x.SubscriptionStartTimestampUTC
	}
	return nil
}

// Deprecated: Marked as deprecated in firm.proto.
func (x *Firm) GetSubscriptionEndTimestampUTC() *timestamppb.Timestamp {
	if x != nil {
		return x.SubscriptionEndTimestampUTC
	}
	return nil
}

func (x *Firm) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *Firm) GetStatusUpdateTimestampUTC() *timestamppb.Timestamp {
	if x != nil {
		return x.StatusUpdateTimestampUTC
	}
	return nil
}

func (x *Firm) GetLastUpdateTimestampUTC() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdateTimestampUTC
	}
	return nil
}

func (x *Firm) GetLastUpdatedByuserId() string {
	if x != nil {
		return x.LastUpdatedByuserId
	}
	return ""
}

func (x *Firm) GetIsMailVerified() bool {
	if x != nil {
		return x.IsMailVerified
	}
	return false
}

func (x *Firm) GetCreationDateUTC() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationDateUTC
	}
	return nil
}

func (x *Firm) GetStripeCustomerId() string {
	if x != nil {
		return x.StripeCustomerId
	}
	return ""
}

func (x *Firm) GetLicenses() []*license.License {
	if x != nil {
		return x.Licenses
	}
	return nil
}

func (x *Firm) GetProviderCustomerIds() map[string]string {
	if x != nil {
		return x.ProviderCustomerIds
	}
	return nil
}

func (x *Firm) GetReferralCode() string {
	if x != nil {
		return x.ReferralCode
	}
	return ""
}

func (x *Firm) GetReferralCreditBalanceCents() int32 {
	if x != nil {
		return x.ReferralCreditBalanceCents
	}
	return 0
}

type CreateFirmRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// / mandatory
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFirmRequest) Reset() {
	*x = CreateFirmRequest{}
	mi := &file_firm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFirmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFirmRequest) ProtoMessage() {}

func (x *CreateFirmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_firm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFirmRequest.ProtoReflect.Descriptor instead.
func (*CreateFirmRequest) Descriptor() ([]byte, []int) {
	return file_firm_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFirmRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateFirmResponse struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	StatusResponse *g_common.StatusResponse `protobuf:"bytes,1,opt,name=statusResponse,proto3" json:"statusResponse,omitempty"`
	Firm           *Firm                    `protobuf:"bytes,2,opt,name=firm,proto3" json:"firm,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateFirmResponse) Reset() {
	*x = CreateFirmResponse{}
	mi := &file_firm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFirmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFirmResponse) ProtoMessage() {}

func (x *CreateFirmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_firm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFirmResponse.ProtoReflect.Descriptor instead.
func (*CreateFirmResponse) Descriptor() ([]byte, []int) {
	return file_firm_proto_rawDescGZIP(), []int{2}
}

func (x *CreateFirmResponse) GetStatusResponse() *g_common.StatusResponse {
	if x != nil {
		return x.StatusResponse
	}
	return nil
}

func (x *CreateFirmResponse) GetFirm() *Firm {
	if x != nil {
		return x.Firm
	}
	return nil
}

var File_firm_proto protoreflect.FileDescriptor

const file_firm_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"firm.proto\x12\n" +
	"weebi.firm\x1a\x18common/g_timestamp.proto\x1a\x15common/g_common.proto\x1a\rlicense.proto\"\xa9\b\n" +
	"\x04Firm\x12\x16\n" +
	"\x06firmId\x18\x01 \x01(\tR\x06firmId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12.\n" +
	"\x10subscriptionPlan\x18\x03 \x01(\tB\x02\x18\x01R\x10subscriptionPlan\x120\n" +
	"\x11subscriptionSeats\x18\x04 \x01(\x05B\x02\x18\x01R\x11subscriptionSeats\x12d\n" +
	"\x1dsubscriptionStartTimestampUTC\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x02\x18\x01R\x1dsubscriptionStartTimestampUTC\x12`\n" +
	"\x1bsubscriptionEndTimestampUTC\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x02\x18\x01R\x1bsubscriptionEndTimestampUTC\x12\x16\n" +
	"\x06status\x18\a \x01(\bR\x06status\x12V\n" +
	"\x18statusUpdateTimestampUTC\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x18statusUpdateTimestampUTC\x12R\n" +
	"\x16lastUpdateTimestampUTC\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x16lastUpdateTimestampUTC\x120\n" +
	"\x13lastUpdatedByuserId\x18\n" +
	" \x01(\tR\x13lastUpdatedByuserId\x12&\n" +
	"\x0eisMailVerified\x18\v \x01(\bR\x0eisMailVerified\x12D\n" +
	"\x0fcreationDateUTC\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\x0fcreationDateUTC\x12*\n" +
	"\x10stripeCustomerId\x18\r \x01(\tR\x10stripeCustomerId\x122\n" +
	"\blicenses\x18\x0e \x03(\v2\x16.weebi.license.LicenseR\blicenses\x12[\n" +
	"\x13providerCustomerIds\x18\x0f \x03(\v2).weebi.firm.Firm.ProviderCustomerIdsEntryR\x13providerCustomerIds\x12\"\n" +
	"\freferralCode\x18\x10 \x01(\tR\freferralCode\x12>\n" +
	"\x1areferralCreditBalanceCents\x18\x11 \x01(\x05R\x1areferralCreditBalanceCents\x1aF\n" +
	"\x18ProviderCustomerIdsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"'\n" +
	"\x11CreateFirmRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x88\x01\n" +
	"\x12CreateFirmResponse\x12L\n" +
	"\x0estatusResponse\x18\x01 \x01(\v2$.google.retail.common.StatusResponseR\x0estatusResponse\x12$\n" +
	"\x04firm\x18\x02 \x01(\v2\x10.weebi.firm.FirmR\x04firmb\x06proto3"

var (
	file_firm_proto_rawDescOnce sync.Once
	file_firm_proto_rawDescData []byte
)

func file_firm_proto_rawDescGZIP() []byte {
	file_firm_proto_rawDescOnce.Do(func() {
		file_firm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_firm_proto_rawDesc), len(file_firm_proto_rawDesc)))
	})
	return file_firm_proto_rawDescData
}

var file_firm_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_firm_proto_goTypes = []any{
	(*Firm)(nil),                    // 0: weebi.firm.Firm
	(*CreateFirmRequest)(nil),       // 1: weebi.firm.CreateFirmRequest
	(*CreateFirmResponse)(nil),      // 2: weebi.firm.CreateFirmResponse
	nil,                             // 3: weebi.firm.Firm.ProviderCustomerIdsEntry
	(*timestamppb.Timestamp)(nil),   // 4: google.protobuf.Timestamp
	(*license.License)(nil),         // 5: weebi.license.License
	(*g_common.StatusResponse)(nil), // 6: google.retail.common.StatusResponse
}
var file_firm_proto_depIdxs = []int32{
	4, // 0: weebi.firm.Firm.subscriptionStartTimestampUTC:type_name -> google.protobuf.Timestamp
	4, // 1: weebi.firm.Firm.subscriptionEndTimestampUTC:type_name -> google.protobuf.Timestamp
	4, // 2: weebi.firm.Firm.statusUpdateTimestampUTC:type_name -> google.protobuf.Timestamp
	4, // 3: weebi.firm.Firm.lastUpdateTimestampUTC:type_name -> google.protobuf.Timestamp
	4, // 4: weebi.firm.Firm.creationDateUTC:type_name -> google.protobuf.Timestamp
	5, // 5: weebi.firm.Firm.licenses:type_name -> weebi.license.License
	3, // 6: weebi.firm.Firm.providerCustomerIds:type_name -> weebi.firm.Firm.ProviderCustomerIdsEntry
	6, // 7: weebi.firm.CreateFirmResponse.statusResponse:type_name -> google.retail.common.StatusResponse
	0, // 8: weebi.firm.CreateFirmResponse.firm:type_name -> weebi.firm.Firm
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_firm_proto_init() }
func file_firm_proto_init() {
	if File_firm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_firm_proto_rawDesc), len(file_firm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_firm_proto_goTypes,
		DependencyIndexes: file_firm_proto_depIdxs,
		MessageInfos:      file_firm_proto_msgTypes,
	}.Build()
	File_firm_proto = out.File
	file_firm_proto_goTypes = nil
	file_firm_proto_depIdxs = nil
}
