// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: common/chained_ids.proto

package chained_ids

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChainIdAndboutiqueId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       string                 `protobuf:"bytes,1,opt,name=chainId,proto3" json:"chainId,omitempty"`
	BoutiqueId    string                 `protobuf:"bytes,2,opt,name=boutiqueId,proto3" json:"boutiqueId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainIdAndboutiqueId) Reset() {
	*x = ChainIdAndboutiqueId{}
	mi := &file_common_chained_ids_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainIdAndboutiqueId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainIdAndboutiqueId) ProtoMessage() {}

func (x *ChainIdAndboutiqueId) ProtoReflect() protoreflect.Message {
	mi := &file_common_chained_ids_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainIdAndboutiqueId.ProtoReflect.Descriptor instead.
func (*ChainIdAndboutiqueId) Descriptor() ([]byte, []int) {
	return file_common_chained_ids_proto_rawDescGZIP(), []int{0}
}

func (x *ChainIdAndboutiqueId) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *ChainIdAndboutiqueId) GetBoutiqueId() string {
	if x != nil {
		return x.BoutiqueId
	}
	return ""
}

type BoutiqueIndexAndDeviceIndex struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoutiqueIndex int32                  `protobuf:"varint,1,opt,name=boutiqueIndex,proto3" json:"boutiqueIndex,omitempty"`
	DeviceIndex   int32                  `protobuf:"varint,2,opt,name=deviceIndex,proto3" json:"deviceIndex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoutiqueIndexAndDeviceIndex) Reset() {
	*x = BoutiqueIndexAndDeviceIndex{}
	mi := &file_common_chained_ids_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoutiqueIndexAndDeviceIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoutiqueIndexAndDeviceIndex) ProtoMessage() {}

func (x *BoutiqueIndexAndDeviceIndex) ProtoReflect() protoreflect.Message {
	mi := &file_common_chained_ids_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoutiqueIndexAndDeviceIndex.ProtoReflect.Descriptor instead.
func (*BoutiqueIndexAndDeviceIndex) Descriptor() ([]byte, []int) {
	return file_common_chained_ids_proto_rawDescGZIP(), []int{1}
}

func (x *BoutiqueIndexAndDeviceIndex) GetBoutiqueIndex() int32 {
	if x != nil {
		return x.BoutiqueIndex
	}
	return 0
}

func (x *BoutiqueIndexAndDeviceIndex) GetDeviceIndex() int32 {
	if x != nil {
		return x.DeviceIndex
	}
	return 0
}

var File_common_chained_ids_proto protoreflect.FileDescriptor

const file_common_chained_ids_proto_rawDesc = "" +
	"\n" +
	"\x18common/chained_ids.proto\x12\x18weebi.common.chained_ids\"P\n" +
	"\x14ChainIdAndboutiqueId\x12\x18\n" +
	"\achainId\x18\x01 \x01(\tR\achainId\x12\x1e\n" +
	"\n" +
	"boutiqueId\x18\x02 \x01(\tR\n" +
	"boutiqueId\"e\n" +
	"\x1bBoutiqueIndexAndDeviceIndex\x12$\n" +
	"\rboutiqueIndex\x18\x01 \x01(\x05R\rboutiqueIndex\x12 \n" +
	"\vdeviceIndex\x18\x02 \x01(\x05R\vdeviceIndexb\x06proto3"

var (
	file_common_chained_ids_proto_rawDescOnce sync.Once
	file_common_chained_ids_proto_rawDescData []byte
)

func file_common_chained_ids_proto_rawDescGZIP() []byte {
	file_common_chained_ids_proto_rawDescOnce.Do(func() {
		file_common_chained_ids_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_chained_ids_proto_rawDesc), len(file_common_chained_ids_proto_rawDesc)))
	})
	return file_common_chained_ids_proto_rawDescData
}

var file_common_chained_ids_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_chained_ids_proto_goTypes = []any{
	(*ChainIdAndboutiqueId)(nil),        // 0: weebi.common.chained_ids.ChainIdAndboutiqueId
	(*BoutiqueIndexAndDeviceIndex)(nil), // 1: weebi.common.chained_ids.BoutiqueIndexAndDeviceIndex
}
var file_common_chained_ids_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_chained_ids_proto_init() }
func file_common_chained_ids_proto_init() {
	if File_common_chained_ids_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_chained_ids_proto_rawDesc), len(file_common_chained_ids_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_chained_ids_proto_goTypes,
		DependencyIndexes: file_common_chained_ids_proto_depIdxs,
		MessageInfos:      file_common_chained_ids_proto_msgTypes,
	}.Build()
	File_common_chained_ids_proto = out.File
	file_common_chained_ids_proto_goTypes = nil
	file_common_chained_ids_proto_depIdxs = nil
}
